// Generated by scripts/generate-tokens.py from design/tokens.toml.
// Do not edit — edit the source and regenerate. CI fails on drift.

package dev.supermessage

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp

/** The sixteen colour roles, one value each. */
@Immutable
data class SupermessageColorRoles(
    val surface: Color,
    /**
     * The sheet-on-field step: the reading column over the roster, header
     * and composer. The whole three-level depth story rests on it, and it is
     * what silently broke in the previous dark theme at 1.035 — less than
     * half the step, and effectively subliminal across 1050px of field.
     */
    val surfaceSunken: Color,
    val surfaceRaised: Color,
    val border: Color,
    val borderStrong: Color,
    val content: Color,
    val contentMuted: Color,
    /**
     * The bottom rung is the whole ramp's constraint. It must clear the
     * floor on all three grounds, not just the reading surface — the earlier
     * cool-slate attempt passed on `surface` and measured 2.92:1 on
     * `surface-sunken`.
     */
    val contentFaint: Color,
    val accent: Color,
    val accentContent: Color,
    val accentSoft: Color,
    /**
     * Amber, and it means exactly one thing: the reader owes someone an
     * answer. 6.0 rather than 4.5 because it carries the 10px AWAITING YOUR
     * DECISION label — the smallest text in the app, on the one element that
     * must not be missed.
     */
    val signal: Color,
    val signalSoft: Color,
    val danger: Color,
    val ok: Color,
    /**
     * Not a fifth hue and not a new rank — the ramp's dark end used as a
     * wash. Checked as a region drop (ground plus the text on it), never as
     * a WCAG ratio and never against one surface: this scrim IS `content`,
     * so measuring it against `content` alone would report 1.00x for a wash
     * that works.
     */
    val scrim: Color,
)

/**
 * The appearances.
 *
 * Android binds `paper` to light and `dark` to dark: paper is what
 * "light" means on a phone. See Theme.kt.
 */
object GeneratedThemeTokens {
    val light = SupermessageColorRoles(
        surface = Color(0xFFFDFCFF),
        surfaceSunken = Color(0xFFF3F2F9),
        surfaceRaised = Color(0xFFFAFAFD),
        border = Color(0xFFE0DEEA),
        borderStrong = Color(0xFFC3BFD4),
        content = Color(0xFF221C38),
        contentMuted = Color(0xFF50496D),
        contentFaint = Color(0xFF70688F),
        accent = Color(0xFF5B43D4),
        accentContent = Color(0xFFFFFFFF),
        accentSoft = Color(0xFFEBE7FB),
        signal = Color(0xFF814904),
        signalSoft = Color(0xFFFCF3E4),
        danger = Color(0xFFB4222A),
        ok = Color(0xFF1D7C59),
        scrim = Color(0x73221C38),
    )

    val dark = SupermessageColorRoles(
        surface = Color(0xFF1F1838),
        surfaceSunken = Color(0xFF151129),
        surfaceRaised = Color(0xFF251F41),
        border = Color(0xFF383254),
        borderStrong = Color(0xFF534A75),
        content = Color(0xFFF4F2FB),
        contentMuted = Color(0xFFC6C2D8),
        contentFaint = Color(0xFF8E86AB),
        accent = Color(0xFF9D8FF0),
        accentContent = Color(0xFF1A1433),
        accentSoft = Color(0xFF2B224F),
        signal = Color(0xFFE8A33D),
        signalSoft = Color(0xFF332919),
        danger = Color(0xFFED6E74),
        ok = Color(0xFF70CDAB),
        scrim = Color(0xB2151129),
    )

    val paper = SupermessageColorRoles(
        surface = Color(0xFFFAF8F3),
        surfaceSunken = Color(0xFFF2EEE6),
        surfaceRaised = Color(0xFFF7F6F1),
        border = Color(0xFFE1DBCD),
        borderStrong = Color(0xFFC5BEA8),
        content = Color(0xFF22192E),
        contentMuted = Color(0xFF51475E),
        contentFaint = Color(0xFF726681),
        accent = Color(0xFF5B43D4),
        accentContent = Color(0xFFFFFFFF),
        accentSoft = Color(0xFFEBE7FB),
        signal = Color(0xFF814904),
        signalSoft = Color(0xFFF7EDDA),
        danger = Color(0xFFB4222A),
        ok = Color(0xFF1D7C59),
        scrim = Color(0x7322192E),
    )

    val black = SupermessageColorRoles(
        surface = Color(0xFF000000),
        surfaceSunken = Color(0xFF100F17),
        surfaceRaised = Color(0xFF1A1824),
        border = Color(0xFF2C2A38),
        borderStrong = Color(0xFF4A4660),
        content = Color(0xFFF4F2FB),
        contentMuted = Color(0xFFC6C2D8),
        contentFaint = Color(0xFF8E86AB),
        accent = Color(0xFF9D8FF0),
        accentContent = Color(0xFF1A1433),
        accentSoft = Color(0xFF241C42),
        signal = Color(0xFFE8A33D),
        signalSoft = Color(0xFF2A2114),
        danger = Color(0xFFED6E74),
        ok = Color(0xFF70CDAB),
        scrim = Color(0xB8000000),
    )
}

/**
 * The accents a reader may choose, per appearance: the whole palette
 * with the accent applied. Violet, the default, is the appearances'
 * own and is not listed.
 */
object GeneratedAccents {
    val names = listOf("blue", "graphite", "green", "pink", "teal")
    val blue = mapOf(
        "light" to SupermessageColorRoles(
            surface = Color(0xFFFBFDFF),
            surfaceSunken = Color(0xFFF0F3FA),
            surfaceRaised = Color(0xFFF9FAFD),
            border = Color(0xFFDAE0EB),
            borderStrong = Color(0xFFB8C3D6),
            content = Color(0xFF13213A),
            contentMuted = Color(0xFF3D4F70),
            contentFaint = Color(0xFF5B6F92),
            accent = Color(0xFF2356C2),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFE4ECFB),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFFCF3E4),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x73221C38),
        ),
        "dark" to SupermessageColorRoles(
            surface = Color(0xFF161E2E),
            surfaceSunken = Color(0xFF0F1521),
            surfaceRaised = Color(0xFF1C2536),
            border = Color(0xFF2F3849),
            borderStrong = Color(0xFF465267),
            content = Color(0xFFF1F4F8),
            contentMuted = Color(0xFFBFC6D1),
            contentFaint = Color(0xFF828D9F),
            accent = Color(0xFF8AB4FF),
            accentContent = Color(0xFF0D1630),
            accentSoft = Color(0xFF1C2A4D),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF332919),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB2151129),
        ),
        "paper" to SupermessageColorRoles(
            surface = Color(0xFFF6F8FD),
            surfaceSunken = Color(0xFFEAEFF6),
            surfaceRaised = Color(0xFFF3F6FB),
            border = Color(0xFFD4DCE9),
            borderStrong = Color(0xFFB3BFD3),
            content = Color(0xFF131E31),
            contentMuted = Color(0xFF404D62),
            contentFaint = Color(0xFF5D6B85),
            accent = Color(0xFF2356C2),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFE3EAF7),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFF7EDDA),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x7322192E),
        ),
        "black" to SupermessageColorRoles(
            surface = Color(0xFF000000),
            surfaceSunken = Color(0xFF100F17),
            surfaceRaised = Color(0xFF1A1824),
            border = Color(0xFF2C2A38),
            borderStrong = Color(0xFF4A4660),
            content = Color(0xFFF4F2FB),
            contentMuted = Color(0xFFC6C2D8),
            contentFaint = Color(0xFF8E86AB),
            accent = Color(0xFF8AB4FF),
            accentContent = Color(0xFF0D1630),
            accentSoft = Color(0xFF16213D),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF2A2114),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB8000000),
        ),
    )
    val graphite = mapOf(
        "light" to SupermessageColorRoles(
            surface = Color(0xFFFDFCFF),
            surfaceSunken = Color(0xFFF3F3F5),
            surfaceRaised = Color(0xFFFAFAFD),
            border = Color(0xFFE0DFE2),
            borderStrong = Color(0xFFC2C2C5),
            content = Color(0xFF212123),
            contentMuted = Color(0xFF4F4F51),
            contentFaint = Color(0xFF6F6E71),
            accent = Color(0xFF45424F),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFEBEAEF),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFFCF3E4),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x73221C38),
        ),
        "dark" to SupermessageColorRoles(
            surface = Color(0xFF1E1D23),
            surfaceSunken = Color(0xFF16151A),
            surfaceRaised = Color(0xFF25242A),
            border = Color(0xFF38373D),
            borderStrong = Color(0xFF525157),
            content = Color(0xFFF4F3F8),
            contentMuted = Color(0xFFC5C4CB),
            contentFaint = Color(0xFF8C8B92),
            accent = Color(0xFFCBC8D8),
            accentContent = Color(0xFF1C1A24),
            accentSoft = Color(0xFF2E2A3F),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF332919),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB2151129),
        ),
        "paper" to SupermessageColorRoles(
            surface = Color(0xFFF8F8FB),
            surfaceSunken = Color(0xFFEEEEF1),
            surfaceRaised = Color(0xFFF6F5F8),
            border = Color(0xFFDBDBDE),
            borderStrong = Color(0xFFBEBEC0),
            content = Color(0xFF1E1E20),
            contentMuted = Color(0xFF4C4C4E),
            contentFaint = Color(0xFF6B6A6D),
            accent = Color(0xFF45424F),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFEBE8E2),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFF7EDDA),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x7322192E),
        ),
        "black" to SupermessageColorRoles(
            surface = Color(0xFF000000),
            surfaceSunken = Color(0xFF100F17),
            surfaceRaised = Color(0xFF1A1824),
            border = Color(0xFF2C2A38),
            borderStrong = Color(0xFF4A4660),
            content = Color(0xFFF4F2FB),
            contentMuted = Color(0xFFC6C2D8),
            contentFaint = Color(0xFF8E86AB),
            accent = Color(0xFFCBC8D8),
            accentContent = Color(0xFF1C1A24),
            accentSoft = Color(0xFF26242F),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF2A2114),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB8000000),
        ),
    )
    val green = mapOf(
        "light" to SupermessageColorRoles(
            surface = Color(0xFFFBFDFB),
            surfaceSunken = Color(0xFFEFF5EF),
            surfaceRaised = Color(0xFFF9FBF9),
            border = Color(0xFFD9E3DA),
            borderStrong = Color(0xFFB6C8B8),
            content = Color(0xFF0D2812),
            contentMuted = Color(0xFF38583C),
            contentFaint = Color(0xFF557759),
            accent = Color(0xFF2A7A35),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFE2F1E3),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFFCF3E4),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x73221C38),
        ),
        "dark" to SupermessageColorRoles(
            surface = Color(0xFF132315),
            surfaceSunken = Color(0xFF0D190F),
            surfaceRaised = Color(0xFF1A2A1C),
            border = Color(0xFF2D3D2E),
            borderStrong = Color(0xFF445845),
            content = Color(0xFFF1F5F1),
            contentMuted = Color(0xFFBFC9BF),
            contentFaint = Color(0xFF809282),
            accent = Color(0xFF7FD28A),
            accentContent = Color(0xFF0B2410),
            accentSoft = Color(0xFF1A3620),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF332919),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB2151129),
        ),
        "paper" to SupermessageColorRoles(
            surface = Color(0xFFF5FAF5),
            surfaceSunken = Color(0xFFEAF1EA),
            surfaceRaised = Color(0xFFF3F7F3),
            border = Color(0xFFD3DFD4),
            borderStrong = Color(0xFFB2C4B3),
            content = Color(0xFF102312),
            contentMuted = Color(0xFF3E5240),
            contentFaint = Color(0xFF5A725C),
            accent = Color(0xFF2A7A35),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFE1ECDD),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFF7EDDA),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x7322192E),
        ),
        "black" to SupermessageColorRoles(
            surface = Color(0xFF000000),
            surfaceSunken = Color(0xFF100F17),
            surfaceRaised = Color(0xFF1A1824),
            border = Color(0xFF2C2A38),
            borderStrong = Color(0xFF4A4660),
            content = Color(0xFFF4F2FB),
            contentMuted = Color(0xFFC6C2D8),
            contentFaint = Color(0xFF8E86AB),
            accent = Color(0xFF7FD28A),
            accentContent = Color(0xFF0B2410),
            accentSoft = Color(0xFF142B19),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF2A2114),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB8000000),
        ),
    )
    val pink = mapOf(
        "light" to SupermessageColorRoles(
            surface = Color(0xFFFFFCFD),
            surfaceSunken = Color(0xFFF8F1F4),
            surfaceRaised = Color(0xFFFDF9FB),
            border = Color(0xFFE9DCE1),
            borderStrong = Color(0xFFD2BBC5),
            content = Color(0xFF331625),
            contentMuted = Color(0xFF684154),
            contentFaint = Color(0xFF8A6073),
            accent = Color(0xFFB2266A),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFFAE4EE),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFFCF3E4),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x73221C38),
        ),
        "dark" to SupermessageColorRoles(
            surface = Color(0xFF2A1820),
            surfaceSunken = Color(0xFF1E1017),
            surfaceRaised = Color(0xFF321E27),
            border = Color(0xFF45313A),
            borderStrong = Color(0xFF634954),
            content = Color(0xFFF7F2F4),
            contentMuted = Color(0xFFCFC1C7),
            contentFaint = Color(0xFF9B858F),
            accent = Color(0xFFF48FC0),
            accentContent = Color(0xFF330A1F),
            accentSoft = Color(0xFF3D1B2E),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF332919),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB2151129),
        ),
        "paper" to SupermessageColorRoles(
            surface = Color(0xFFFCF6F9),
            surfaceSunken = Color(0xFFF5EBEF),
            surfaceRaised = Color(0xFFFAF4F6),
            border = Color(0xFFE7D6DD),
            borderStrong = Color(0xFFCFB6C1),
            content = Color(0xFF2C1621),
            contentMuted = Color(0xFF5D444F),
            contentFaint = Color(0xFF816270),
            accent = Color(0xFFB2266A),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFF5E3E8),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFF7EDDA),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x7322192E),
        ),
        "black" to SupermessageColorRoles(
            surface = Color(0xFF000000),
            surfaceSunken = Color(0xFF100F17),
            surfaceRaised = Color(0xFF1A1824),
            border = Color(0xFF2C2A38),
            borderStrong = Color(0xFF4A4660),
            content = Color(0xFFF4F2FB),
            contentMuted = Color(0xFFC6C2D8),
            contentFaint = Color(0xFF8E86AB),
            accent = Color(0xFFF48FC0),
            accentContent = Color(0xFF330A1F),
            accentSoft = Color(0xFF321625),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF2A2114),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB8000000),
        ),
    )
    val teal = mapOf(
        "light" to SupermessageColorRoles(
            surface = Color(0xFFFAFEFD),
            surfaceSunken = Color(0xFFECF5F5),
            surfaceRaised = Color(0xFFF7FBFB),
            border = Color(0xFFD4E3E3),
            borderStrong = Color(0xFFADC9C8),
            content = Color(0xFF002929),
            contentMuted = Color(0xFF1F5959),
            contentFaint = Color(0xFF3E7878),
            accent = Color(0xFF0B6E75),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFDDF1F1),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFFCF3E4),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x73221C38),
        ),
        "dark" to SupermessageColorRoles(
            surface = Color(0xFF072323),
            surfaceSunken = Color(0xFF051919),
            surfaceRaised = Color(0xFF0E2A2A),
            border = Color(0xFF233D3D),
            borderStrong = Color(0xFF375958),
            content = Color(0xFFEFF5F5),
            contentMuted = Color(0xFFBAC9C9),
            contentFaint = Color(0xFF779292),
            accent = Color(0xFF5FCFCF),
            accentContent = Color(0xFF062628),
            accentSoft = Color(0xFF153739),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF332919),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB2151129),
        ),
        "paper" to SupermessageColorRoles(
            surface = Color(0xFFF3FAFA),
            surfaceSunken = Color(0xFFE6F1F1),
            surfaceRaised = Color(0xFFF1F7F7),
            border = Color(0xFFCDE0E0),
            borderStrong = Color(0xFFA8C5C4),
            content = Color(0xFF002424),
            contentMuted = Color(0xFF315353),
            contentFaint = Color(0xFF4A7271),
            accent = Color(0xFF0B6E75),
            accentContent = Color(0xFFFFFFFF),
            accentSoft = Color(0xFFDCECE9),
            signal = Color(0xFF814904),
            signalSoft = Color(0xFFF7EDDA),
            danger = Color(0xFFB4222A),
            ok = Color(0xFF1D7C59),
            scrim = Color(0x7322192E),
        ),
        "black" to SupermessageColorRoles(
            surface = Color(0xFF000000),
            surfaceSunken = Color(0xFF100F17),
            surfaceRaised = Color(0xFF1A1824),
            border = Color(0xFF2C2A38),
            borderStrong = Color(0xFF4A4660),
            content = Color(0xFFF4F2FB),
            contentMuted = Color(0xFFC6C2D8),
            contentFaint = Color(0xFF8E86AB),
            accent = Color(0xFF5FCFCF),
            accentContent = Color(0xFF062628),
            accentSoft = Color(0xFF112C2E),
            signal = Color(0xFFE8A33D),
            signalSoft = Color(0xFF2A2114),
            danger = Color(0xFFED6E74),
            ok = Color(0xFF70CDAB),
            scrim = Color(0xB8000000),
        ),
    )
}

/** One colour per person, indexed by the core's `peerColorIndex`. */
object GeneratedPeers {
    val light = listOf(Color(0xFFB3261E), Color(0xFF6A3FC8), Color(0xFF2D7A36), Color(0xFF0B6F86), Color(0xFF2356C2), Color(0xFFB0306E), Color(0xFF555266))
    val paper = listOf(Color(0xFFB3261E), Color(0xFF6A3FC8), Color(0xFF2D7A36), Color(0xFF0B6F86), Color(0xFF2356C2), Color(0xFFB0306E), Color(0xFF555266))
    val dark = listOf(Color(0xFFF28B82), Color(0xFFB9A4FF), Color(0xFF7FD28A), Color(0xFF6CD0E6), Color(0xFF8AB4FF), Color(0xFFF48FC0), Color(0xFFB7B4C7))
    val black = listOf(Color(0xFFF28B82), Color(0xFFB9A4FF), Color(0xFF7FD28A), Color(0xFF6CD0E6), Color(0xFF8AB4FF), Color(0xFFF48FC0), Color(0xFFB7B4C7))
}

/**
 * The type ranks: a face, and the Material type-scale name that
 * carries the size.
 *
 * The size is a NAME rather than a number so it scales with the
 * reader's font-size setting. A hardcoded `.sp` here would ignore it,
 * and would look correct to whoever wrote it.
 */
object ThemeType {
    val label = FontFamily.SansSerif
    const val labelStyle = "labelSmall"
    val meta = FontFamily.SansSerif
    const val metaStyle = "labelMedium"
    val ui = FontFamily.SansSerif
    const val uiStyle = "bodySmall"
    val uiLg = FontFamily.SansSerif
    const val uiLgStyle = "titleSmall"
    val avatar = FontFamily.SansSerif
    const val avatarStyle = "headlineSmall"
    val body = FontFamily.SansSerif
    const val bodyStyle = "bodyLarge"
    val longread = FontFamily.Serif
    const val longreadStyle = "bodyLarge"
    val bodyOwn = FontFamily.SansSerif
    const val bodyOwnStyle = "bodyMedium"
}

/**
 * Radius, elevation and layout, in dp.
 *
 * The pane breakpoints are computed from the pane widths rather than
 * written down. RootScaffold measures its own width instead — see the
 * design's open questions on the three platforms disagreeing here.
 */
object Metrics {
    val radiusControl = 6.dp
    val radiusCard = 8.dp
    val radiusPill = 9999.dp
    val radiusSharp = 0.dp
    val overlayElevation = 8.dp
    val rosterWidth = 288.dp
    val panelWidth = 320.dp
    val sheetWidth = 630.dp
    val railWidth = 56.dp
    val panelColumn = 1238.dp
    val panelColumnWithRail = 1294.dp
}
