// Generated by scripts/generate-tokens.py from design/tokens.toml.
// Do not edit — edit the source and regenerate. CI fails on drift.

package dev.supermessage

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp

/** The sixteen colour roles, one value each. */
@Immutable
data class SupermessageColorRoles(
    val surface: Color,
    /**
     * The sheet-on-field step: the reading column over the roster, header
     * and composer. The whole three-level depth story rests on it, and it is
     * what silently broke in the previous dark theme at 1.035 — less than
     * half the step, and effectively subliminal across 1050px of field.
     */
    val surfaceSunken: Color,
    val surfaceRaised: Color,
    val border: Color,
    val borderStrong: Color,
    val content: Color,
    val contentMuted: Color,
    /**
     * The bottom rung is the whole ramp's constraint. It must clear the
     * floor on all three grounds, not just the reading surface — the earlier
     * cool-slate attempt passed on `surface` and measured 2.92:1 on
     * `surface-sunken`.
     */
    val contentFaint: Color,
    val accent: Color,
    val accentContent: Color,
    val accentSoft: Color,
    /**
     * Amber, and it means exactly one thing: the reader owes someone an
     * answer. 6.0 rather than 4.5 because it carries the 10px AWAITING YOUR
     * DECISION label — the smallest text in the app, on the one element that
     * must not be missed.
     */
    val signal: Color,
    val signalSoft: Color,
    val danger: Color,
    val ok: Color,
    /**
     * Not a fifth hue and not a new rank — the ramp's dark end used as a
     * wash. Checked as a region drop (ground plus the text on it), never as
     * a WCAG ratio and never against one surface: this scrim IS `content`,
     * so measuring it against `content` alone would report 1.00x for a wash
     * that works.
     */
    val scrim: Color,
)

/**
 * The three appearances.
 *
 * Android binds `paper` to light and `dark` to dark: paper is what
 * "light" means on a phone. There is no picker — see Theme.kt.
 */
object GeneratedThemeTokens {
    val light = SupermessageColorRoles(
        surface = Color(0xFFFDFCFF),
        surfaceSunken = Color(0xFFF3F2F9),
        surfaceRaised = Color(0xFFFAFAFD),
        border = Color(0xFFE0DEEA),
        borderStrong = Color(0xFFC3BFD4),
        content = Color(0xFF221C38),
        contentMuted = Color(0xFF50496D),
        contentFaint = Color(0xFF70688F),
        accent = Color(0xFF5B43D4),
        accentContent = Color(0xFFFFFFFF),
        accentSoft = Color(0xFFEBE7FB),
        signal = Color(0xFF814904),
        signalSoft = Color(0xFFFCF3E4),
        danger = Color(0xFFB4222A),
        ok = Color(0xFF1D7C59),
        scrim = Color(0x73221C38),
    )

    val dark = SupermessageColorRoles(
        surface = Color(0xFF1F1838),
        surfaceSunken = Color(0xFF151129),
        surfaceRaised = Color(0xFF251F41),
        border = Color(0xFF383254),
        borderStrong = Color(0xFF534A75),
        content = Color(0xFFF4F2FB),
        contentMuted = Color(0xFFC6C2D8),
        contentFaint = Color(0xFF8E86AB),
        accent = Color(0xFF9D8FF0),
        accentContent = Color(0xFF1A1433),
        accentSoft = Color(0xFF2B224F),
        signal = Color(0xFFE8A33D),
        signalSoft = Color(0xFF332919),
        danger = Color(0xFFED6E74),
        ok = Color(0xFF70CDAB),
        scrim = Color(0xB2151129),
    )

    val paper = SupermessageColorRoles(
        surface = Color(0xFFFAF8F3),
        surfaceSunken = Color(0xFFF2EEE6),
        surfaceRaised = Color(0xFFF7F6F1),
        border = Color(0xFFE1DBCD),
        borderStrong = Color(0xFFC5BEA8),
        content = Color(0xFF22192E),
        contentMuted = Color(0xFF51475E),
        contentFaint = Color(0xFF726681),
        accent = Color(0xFF5B43D4),
        accentContent = Color(0xFFFFFFFF),
        accentSoft = Color(0xFFEBE7FB),
        signal = Color(0xFF814904),
        signalSoft = Color(0xFFF7EDDA),
        danger = Color(0xFFB4222A),
        ok = Color(0xFF1D7C59),
        scrim = Color(0x7322192E),
    )
}

/**
 * The type ranks: a face, and the Material type-scale name that
 * carries the size.
 *
 * The size is a NAME rather than a number so it scales with the
 * reader's font-size setting. A hardcoded `.sp` here would ignore it,
 * and would look correct to whoever wrote it.
 */
object ThemeType {
    val label = FontFamily.Monospace
    const val labelStyle = "labelSmall"
    val meta = FontFamily.Monospace
    const val metaStyle = "labelMedium"
    val ui = FontFamily.SansSerif
    const val uiStyle = "bodySmall"
    val uiLg = FontFamily.SansSerif
    const val uiLgStyle = "titleSmall"
    val avatar = FontFamily.SansSerif
    const val avatarStyle = "headlineSmall"
    val body = FontFamily.Serif
    const val bodyStyle = "bodyLarge"
    val bodyOwn = FontFamily.SansSerif
    const val bodyOwnStyle = "bodyMedium"
}

/**
 * Radius, elevation and layout, in dp.
 *
 * The pane breakpoints are computed from the pane widths rather than
 * written down. RootScaffold measures its own width instead — see the
 * design's open questions on the three platforms disagreeing here.
 */
object Metrics {
    val radiusControl = 6.dp
    val radiusCard = 8.dp
    val radiusPill = 9999.dp
    val radiusSharp = 0.dp
    val overlayElevation = 8.dp
    val rosterWidth = 288.dp
    val panelWidth = 320.dp
    val sheetWidth = 630.dp
    val railWidth = 56.dp
    val panelColumn = 1238.dp
    val panelColumnWithRail = 1294.dp
}
