// Generated by scripts/generate-tokens.py from design/tokens.toml.
// Do not edit — edit the source and regenerate. CI fails on drift.

import SwiftUI

/// The sixteen colour roles, one value each.
struct Palette {
    let surface: Color
    /// The sheet-on-field step: the reading column over the roster, header and
    /// composer. The whole three-level depth story rests on it, and it is what
    /// silently broke in the previous dark theme at 1.035 — less than half the
    /// step, and effectively subliminal across 1050px of field.
    let surfaceSunken: Color
    let surfaceRaised: Color
    let border: Color
    let borderStrong: Color
    let content: Color
    let contentMuted: Color
    /// The bottom rung is the whole ramp's constraint. It must clear the floor
    /// on all three grounds, not just the reading surface — the earlier cool-
    /// slate attempt passed on `surface` and measured 2.92:1 on `surface-
    /// sunken`.
    let contentFaint: Color
    let accent: Color
    let accentContent: Color
    let accentSoft: Color
    /// Amber, and it means exactly one thing: the reader owes someone an
    /// answer. 6.0 rather than 4.5 because it carries the 10px AWAITING YOUR
    /// DECISION label — the smallest text in the app, on the one element that
    /// must not be missed.
    let signal: Color
    let signalSoft: Color
    let danger: Color
    let ok: Color
    /// Not a fifth hue and not a new rank — the ramp's dark end used as a wash.
    /// Checked as a region drop (ground plus the text on it), never as a WCAG
    /// ratio and never against one surface: this scrim IS `content`, so
    /// measuring it against `content` alone would report 1.00x for a wash that
    /// works.
    let scrim: Color
}

/// The appearances.
///
/// iOS binds `paper` to light and `dark` (or `black`, the reader's
/// choice) to dark — see Theme.swift.
enum ThemeTokens {
    static let light = Palette(
        surface: Color(.sRGB, red: 0.9922, green: 0.9882, blue: 1.0000, opacity: 1),
        surfaceSunken: Color(.sRGB, red: 0.9529, green: 0.9490, blue: 0.9765, opacity: 1),
        surfaceRaised: Color(.sRGB, red: 0.9804, green: 0.9804, blue: 0.9922, opacity: 1),
        border: Color(.sRGB, red: 0.8784, green: 0.8706, blue: 0.9176, opacity: 1),
        borderStrong: Color(.sRGB, red: 0.7647, green: 0.7490, blue: 0.8314, opacity: 1),
        content: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 1),
        contentMuted: Color(.sRGB, red: 0.3137, green: 0.2863, blue: 0.4275, opacity: 1),
        contentFaint: Color(.sRGB, red: 0.4392, green: 0.4078, blue: 0.5608, opacity: 1),
        accent: Color(.sRGB, red: 0.3569, green: 0.2627, blue: 0.8314, opacity: 1),
        accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
        accentSoft: Color(.sRGB, red: 0.9216, green: 0.9059, blue: 0.9843, opacity: 1),
        signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
        signalSoft: Color(.sRGB, red: 0.9882, green: 0.9529, blue: 0.8941, opacity: 1),
        danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
        ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
        scrim: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 0.45)
    )

    static let dark = Palette(
        surface: Color(.sRGB, red: 0.1216, green: 0.0941, blue: 0.2196, opacity: 1),
        surfaceSunken: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 1),
        surfaceRaised: Color(.sRGB, red: 0.1451, green: 0.1216, blue: 0.2549, opacity: 1),
        border: Color(.sRGB, red: 0.2196, green: 0.1961, blue: 0.3294, opacity: 1),
        borderStrong: Color(.sRGB, red: 0.3255, green: 0.2902, blue: 0.4588, opacity: 1),
        content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
        contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
        contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
        accent: Color(.sRGB, red: 0.6157, green: 0.5608, blue: 0.9412, opacity: 1),
        accentContent: Color(.sRGB, red: 0.1020, green: 0.0784, blue: 0.2000, opacity: 1),
        accentSoft: Color(.sRGB, red: 0.1686, green: 0.1333, blue: 0.3098, opacity: 1),
        signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
        signalSoft: Color(.sRGB, red: 0.2000, green: 0.1608, blue: 0.0980, opacity: 1),
        danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
        ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
        scrim: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 0.7)
    )

    static let paper = Palette(
        surface: Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9529, opacity: 1),
        surfaceSunken: Color(.sRGB, red: 0.9490, green: 0.9333, blue: 0.9020, opacity: 1),
        surfaceRaised: Color(.sRGB, red: 0.9686, green: 0.9647, blue: 0.9451, opacity: 1),
        border: Color(.sRGB, red: 0.8824, green: 0.8588, blue: 0.8039, opacity: 1),
        borderStrong: Color(.sRGB, red: 0.7725, green: 0.7451, blue: 0.6588, opacity: 1),
        content: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 1),
        contentMuted: Color(.sRGB, red: 0.3176, green: 0.2784, blue: 0.3686, opacity: 1),
        contentFaint: Color(.sRGB, red: 0.4471, green: 0.4000, blue: 0.5059, opacity: 1),
        accent: Color(.sRGB, red: 0.3569, green: 0.2627, blue: 0.8314, opacity: 1),
        accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
        accentSoft: Color(.sRGB, red: 0.9216, green: 0.9059, blue: 0.9843, opacity: 1),
        signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
        signalSoft: Color(.sRGB, red: 0.9686, green: 0.9294, blue: 0.8549, opacity: 1),
        danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
        ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
        scrim: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 0.45)
    )

    static let black = Palette(
        surface: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
        surfaceSunken: Color(.sRGB, red: 0.0627, green: 0.0588, blue: 0.0902, opacity: 1),
        surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.0941, blue: 0.1412, opacity: 1),
        border: Color(.sRGB, red: 0.1725, green: 0.1647, blue: 0.2196, opacity: 1),
        borderStrong: Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.3765, opacity: 1),
        content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
        contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
        contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
        accent: Color(.sRGB, red: 0.6157, green: 0.5608, blue: 0.9412, opacity: 1),
        accentContent: Color(.sRGB, red: 0.1020, green: 0.0784, blue: 0.2000, opacity: 1),
        accentSoft: Color(.sRGB, red: 0.1412, green: 0.1098, blue: 0.2588, opacity: 1),
        signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
        signalSoft: Color(.sRGB, red: 0.1647, green: 0.1294, blue: 0.0784, opacity: 1),
        danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
        ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
        scrim: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.72)
    )
}

/// One accent, in every appearance: the whole palette with the accent
/// applied — its own accent roles, and grounds and greys in its hue.
struct AccentSet {
    let light: Palette
    let dark: Palette
    let paper: Palette
    let black: Palette
}

/// The accents a reader may choose. Violet, the default, is the
/// appearances' own and is not listed.
enum ThemeAccents {
    static let names = ["blue", "graphite", "green", "pink", "teal"]
    static let blue = AccentSet(
        light: Palette(
            surface: Color(.sRGB, red: 0.9843, green: 0.9922, blue: 1.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9412, green: 0.9529, blue: 0.9804, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9765, green: 0.9804, blue: 0.9922, opacity: 1),
            border: Color(.sRGB, red: 0.8549, green: 0.8784, blue: 0.9216, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.7216, green: 0.7647, blue: 0.8392, opacity: 1),
            content: Color(.sRGB, red: 0.0745, green: 0.1294, blue: 0.2275, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.2392, green: 0.3098, blue: 0.4392, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.3569, green: 0.4353, blue: 0.5725, opacity: 1),
            accent: Color(.sRGB, red: 0.1373, green: 0.3373, blue: 0.7608, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.8941, green: 0.9255, blue: 0.9843, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9882, green: 0.9529, blue: 0.8941, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 0.45)
        ),
        dark: Palette(
            surface: Color(.sRGB, red: 0.0863, green: 0.1176, blue: 0.1804, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0588, green: 0.0824, blue: 0.1294, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1098, green: 0.1451, blue: 0.2118, opacity: 1),
            border: Color(.sRGB, red: 0.1843, green: 0.2196, blue: 0.2863, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2745, green: 0.3216, blue: 0.4039, opacity: 1),
            content: Color(.sRGB, red: 0.9451, green: 0.9569, blue: 0.9725, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7490, green: 0.7765, blue: 0.8196, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5098, green: 0.5529, blue: 0.6235, opacity: 1),
            accent: Color(.sRGB, red: 0.5412, green: 0.7059, blue: 1.0000, opacity: 1),
            accentContent: Color(.sRGB, red: 0.0510, green: 0.0863, blue: 0.1882, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.1098, green: 0.1647, blue: 0.3020, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.2000, green: 0.1608, blue: 0.0980, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 0.7)
        ),
        paper: Palette(
            surface: Color(.sRGB, red: 0.9647, green: 0.9725, blue: 0.9922, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9176, green: 0.9373, blue: 0.9647, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9529, green: 0.9647, blue: 0.9843, opacity: 1),
            border: Color(.sRGB, red: 0.8314, green: 0.8627, blue: 0.9137, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.7020, green: 0.7490, blue: 0.8275, opacity: 1),
            content: Color(.sRGB, red: 0.0745, green: 0.1176, blue: 0.1922, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.2510, green: 0.3020, blue: 0.3843, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.3647, green: 0.4196, blue: 0.5216, opacity: 1),
            accent: Color(.sRGB, red: 0.1373, green: 0.3373, blue: 0.7608, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.8902, green: 0.9176, blue: 0.9686, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9686, green: 0.9294, blue: 0.8549, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 0.45)
        ),
        black: Palette(
            surface: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0627, green: 0.0588, blue: 0.0902, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.0941, blue: 0.1412, opacity: 1),
            border: Color(.sRGB, red: 0.1725, green: 0.1647, blue: 0.2196, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.3765, opacity: 1),
            content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
            accent: Color(.sRGB, red: 0.5412, green: 0.7059, blue: 1.0000, opacity: 1),
            accentContent: Color(.sRGB, red: 0.0510, green: 0.0863, blue: 0.1882, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.0863, green: 0.1294, blue: 0.2392, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.1647, green: 0.1294, blue: 0.0784, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.72)
        )
    )
    static let graphite = AccentSet(
        light: Palette(
            surface: Color(.sRGB, red: 0.9922, green: 0.9882, blue: 1.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9529, green: 0.9529, blue: 0.9608, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9804, green: 0.9804, blue: 0.9922, opacity: 1),
            border: Color(.sRGB, red: 0.8784, green: 0.8745, blue: 0.8863, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.7608, green: 0.7608, blue: 0.7725, opacity: 1),
            content: Color(.sRGB, red: 0.1294, green: 0.1294, blue: 0.1373, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.3098, green: 0.3098, blue: 0.3176, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.4353, green: 0.4314, blue: 0.4431, opacity: 1),
            accent: Color(.sRGB, red: 0.2706, green: 0.2588, blue: 0.3098, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.9216, green: 0.9176, blue: 0.9373, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9882, green: 0.9529, blue: 0.8941, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 0.45)
        ),
        dark: Palette(
            surface: Color(.sRGB, red: 0.1176, green: 0.1137, blue: 0.1373, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0863, green: 0.0824, blue: 0.1020, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1451, green: 0.1412, blue: 0.1647, opacity: 1),
            border: Color(.sRGB, red: 0.2196, green: 0.2157, blue: 0.2392, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.3216, green: 0.3176, blue: 0.3412, opacity: 1),
            content: Color(.sRGB, red: 0.9569, green: 0.9529, blue: 0.9725, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7725, green: 0.7686, blue: 0.7961, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5490, green: 0.5451, blue: 0.5725, opacity: 1),
            accent: Color(.sRGB, red: 0.7961, green: 0.7843, blue: 0.8471, opacity: 1),
            accentContent: Color(.sRGB, red: 0.1098, green: 0.1020, blue: 0.1412, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.1804, green: 0.1647, blue: 0.2471, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.2000, green: 0.1608, blue: 0.0980, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 0.7)
        ),
        paper: Palette(
            surface: Color(.sRGB, red: 0.9725, green: 0.9725, blue: 0.9843, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9333, green: 0.9333, blue: 0.9451, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9647, green: 0.9608, blue: 0.9725, opacity: 1),
            border: Color(.sRGB, red: 0.8588, green: 0.8588, blue: 0.8706, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.7451, green: 0.7451, blue: 0.7529, opacity: 1),
            content: Color(.sRGB, red: 0.1176, green: 0.1176, blue: 0.1255, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.2980, green: 0.2980, blue: 0.3059, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.4196, green: 0.4157, blue: 0.4275, opacity: 1),
            accent: Color(.sRGB, red: 0.2706, green: 0.2588, blue: 0.3098, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.9216, green: 0.9098, blue: 0.8863, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9686, green: 0.9294, blue: 0.8549, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 0.45)
        ),
        black: Palette(
            surface: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0627, green: 0.0588, blue: 0.0902, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.0941, blue: 0.1412, opacity: 1),
            border: Color(.sRGB, red: 0.1725, green: 0.1647, blue: 0.2196, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.3765, opacity: 1),
            content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
            accent: Color(.sRGB, red: 0.7961, green: 0.7843, blue: 0.8471, opacity: 1),
            accentContent: Color(.sRGB, red: 0.1098, green: 0.1020, blue: 0.1412, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.1490, green: 0.1412, blue: 0.1843, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.1647, green: 0.1294, blue: 0.0784, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.72)
        )
    )
    static let green = AccentSet(
        light: Palette(
            surface: Color(.sRGB, red: 0.9843, green: 0.9922, blue: 0.9843, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9373, green: 0.9608, blue: 0.9373, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9765, green: 0.9843, blue: 0.9765, opacity: 1),
            border: Color(.sRGB, red: 0.8510, green: 0.8902, blue: 0.8549, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.7137, green: 0.7843, blue: 0.7216, opacity: 1),
            content: Color(.sRGB, red: 0.0510, green: 0.1569, blue: 0.0706, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.2196, green: 0.3451, blue: 0.2353, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.3333, green: 0.4667, blue: 0.3490, opacity: 1),
            accent: Color(.sRGB, red: 0.1647, green: 0.4784, blue: 0.2078, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.8863, green: 0.9451, blue: 0.8902, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9882, green: 0.9529, blue: 0.8941, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 0.45)
        ),
        dark: Palette(
            surface: Color(.sRGB, red: 0.0745, green: 0.1373, blue: 0.0824, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0510, green: 0.0980, blue: 0.0588, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.1647, blue: 0.1098, opacity: 1),
            border: Color(.sRGB, red: 0.1765, green: 0.2392, blue: 0.1804, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2667, green: 0.3451, blue: 0.2706, opacity: 1),
            content: Color(.sRGB, red: 0.9451, green: 0.9608, blue: 0.9451, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7490, green: 0.7882, blue: 0.7490, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5020, green: 0.5725, blue: 0.5098, opacity: 1),
            accent: Color(.sRGB, red: 0.4980, green: 0.8235, blue: 0.5412, opacity: 1),
            accentContent: Color(.sRGB, red: 0.0431, green: 0.1412, blue: 0.0627, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.1020, green: 0.2118, blue: 0.1255, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.2000, green: 0.1608, blue: 0.0980, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 0.7)
        ),
        paper: Palette(
            surface: Color(.sRGB, red: 0.9608, green: 0.9804, blue: 0.9608, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9176, green: 0.9451, blue: 0.9176, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9529, green: 0.9686, blue: 0.9529, opacity: 1),
            border: Color(.sRGB, red: 0.8275, green: 0.8745, blue: 0.8314, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.6980, green: 0.7686, blue: 0.7020, opacity: 1),
            content: Color(.sRGB, red: 0.0627, green: 0.1373, blue: 0.0706, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.2431, green: 0.3216, blue: 0.2510, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.3529, green: 0.4471, blue: 0.3608, opacity: 1),
            accent: Color(.sRGB, red: 0.1647, green: 0.4784, blue: 0.2078, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.8824, green: 0.9255, blue: 0.8667, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9686, green: 0.9294, blue: 0.8549, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 0.45)
        ),
        black: Palette(
            surface: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0627, green: 0.0588, blue: 0.0902, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.0941, blue: 0.1412, opacity: 1),
            border: Color(.sRGB, red: 0.1725, green: 0.1647, blue: 0.2196, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.3765, opacity: 1),
            content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
            accent: Color(.sRGB, red: 0.4980, green: 0.8235, blue: 0.5412, opacity: 1),
            accentContent: Color(.sRGB, red: 0.0431, green: 0.1412, blue: 0.0627, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.0784, green: 0.1686, blue: 0.0980, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.1647, green: 0.1294, blue: 0.0784, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.72)
        )
    )
    static let pink = AccentSet(
        light: Palette(
            surface: Color(.sRGB, red: 1.0000, green: 0.9882, blue: 0.9922, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9725, green: 0.9451, blue: 0.9569, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9922, green: 0.9765, blue: 0.9843, opacity: 1),
            border: Color(.sRGB, red: 0.9137, green: 0.8627, blue: 0.8824, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.8235, green: 0.7333, blue: 0.7725, opacity: 1),
            content: Color(.sRGB, red: 0.2000, green: 0.0863, blue: 0.1451, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.4078, green: 0.2549, blue: 0.3294, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5412, green: 0.3765, blue: 0.4510, opacity: 1),
            accent: Color(.sRGB, red: 0.6980, green: 0.1490, blue: 0.4157, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.9804, green: 0.8941, blue: 0.9333, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9882, green: 0.9529, blue: 0.8941, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 0.45)
        ),
        dark: Palette(
            surface: Color(.sRGB, red: 0.1647, green: 0.0941, blue: 0.1255, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.1176, green: 0.0627, blue: 0.0902, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1961, green: 0.1176, blue: 0.1529, opacity: 1),
            border: Color(.sRGB, red: 0.2706, green: 0.1922, blue: 0.2275, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.3882, green: 0.2863, blue: 0.3294, opacity: 1),
            content: Color(.sRGB, red: 0.9686, green: 0.9490, blue: 0.9569, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.8118, green: 0.7569, blue: 0.7804, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.6078, green: 0.5216, blue: 0.5608, opacity: 1),
            accent: Color(.sRGB, red: 0.9569, green: 0.5608, blue: 0.7529, opacity: 1),
            accentContent: Color(.sRGB, red: 0.2000, green: 0.0392, blue: 0.1216, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.2392, green: 0.1059, blue: 0.1804, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.2000, green: 0.1608, blue: 0.0980, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 0.7)
        ),
        paper: Palette(
            surface: Color(.sRGB, red: 0.9882, green: 0.9647, blue: 0.9765, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9608, green: 0.9216, blue: 0.9373, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9804, green: 0.9569, blue: 0.9647, opacity: 1),
            border: Color(.sRGB, red: 0.9059, green: 0.8392, blue: 0.8667, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.8118, green: 0.7137, blue: 0.7569, opacity: 1),
            content: Color(.sRGB, red: 0.1725, green: 0.0863, blue: 0.1294, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.3647, green: 0.2667, blue: 0.3098, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5059, green: 0.3843, blue: 0.4392, opacity: 1),
            accent: Color(.sRGB, red: 0.6980, green: 0.1490, blue: 0.4157, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.9608, green: 0.8902, blue: 0.9098, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9686, green: 0.9294, blue: 0.8549, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 0.45)
        ),
        black: Palette(
            surface: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0627, green: 0.0588, blue: 0.0902, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.0941, blue: 0.1412, opacity: 1),
            border: Color(.sRGB, red: 0.1725, green: 0.1647, blue: 0.2196, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.3765, opacity: 1),
            content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
            accent: Color(.sRGB, red: 0.9569, green: 0.5608, blue: 0.7529, opacity: 1),
            accentContent: Color(.sRGB, red: 0.2000, green: 0.0392, blue: 0.1216, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.1961, green: 0.0863, blue: 0.1451, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.1647, green: 0.1294, blue: 0.0784, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.72)
        )
    )
    static let teal = AccentSet(
        light: Palette(
            surface: Color(.sRGB, red: 0.9804, green: 0.9961, blue: 0.9922, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9255, green: 0.9608, blue: 0.9608, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9686, green: 0.9843, blue: 0.9843, opacity: 1),
            border: Color(.sRGB, red: 0.8314, green: 0.8902, blue: 0.8902, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.6784, green: 0.7882, blue: 0.7843, opacity: 1),
            content: Color(.sRGB, red: 0.0000, green: 0.1608, blue: 0.1608, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.1216, green: 0.3490, blue: 0.3490, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.2431, green: 0.4706, blue: 0.4706, opacity: 1),
            accent: Color(.sRGB, red: 0.0431, green: 0.4314, blue: 0.4588, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.8667, green: 0.9451, blue: 0.9451, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9882, green: 0.9529, blue: 0.8941, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.1098, blue: 0.2196, opacity: 0.45)
        ),
        dark: Palette(
            surface: Color(.sRGB, red: 0.0275, green: 0.1373, blue: 0.1373, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0196, green: 0.0980, blue: 0.0980, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.0549, green: 0.1647, blue: 0.1647, opacity: 1),
            border: Color(.sRGB, red: 0.1373, green: 0.2392, blue: 0.2392, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2157, green: 0.3490, blue: 0.3451, opacity: 1),
            content: Color(.sRGB, red: 0.9373, green: 0.9608, blue: 0.9608, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7294, green: 0.7882, blue: 0.7882, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.4667, green: 0.5725, blue: 0.5725, opacity: 1),
            accent: Color(.sRGB, red: 0.3725, green: 0.8118, blue: 0.8118, opacity: 1),
            accentContent: Color(.sRGB, red: 0.0235, green: 0.1490, blue: 0.1569, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.0824, green: 0.2157, blue: 0.2235, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.2000, green: 0.1608, blue: 0.0980, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0824, green: 0.0667, blue: 0.1608, opacity: 0.7)
        ),
        paper: Palette(
            surface: Color(.sRGB, red: 0.9529, green: 0.9804, blue: 0.9804, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.9020, green: 0.9451, blue: 0.9451, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.9451, green: 0.9686, blue: 0.9686, opacity: 1),
            border: Color(.sRGB, red: 0.8039, green: 0.8784, blue: 0.8784, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.6588, green: 0.7725, blue: 0.7686, opacity: 1),
            content: Color(.sRGB, red: 0.0000, green: 0.1412, blue: 0.1412, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.1922, green: 0.3255, blue: 0.3255, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.2902, green: 0.4471, blue: 0.4431, opacity: 1),
            accent: Color(.sRGB, red: 0.0431, green: 0.4314, blue: 0.4588, opacity: 1),
            accentContent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.8627, green: 0.9255, blue: 0.9137, opacity: 1),
            signal: Color(.sRGB, red: 0.5059, green: 0.2863, blue: 0.0157, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.9686, green: 0.9294, blue: 0.8549, opacity: 1),
            danger: Color(.sRGB, red: 0.7059, green: 0.1333, blue: 0.1647, opacity: 1),
            ok: Color(.sRGB, red: 0.1137, green: 0.4863, blue: 0.3490, opacity: 1),
            scrim: Color(.sRGB, red: 0.1333, green: 0.0980, blue: 0.1804, opacity: 0.45)
        ),
        black: Palette(
            surface: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
            surfaceSunken: Color(.sRGB, red: 0.0627, green: 0.0588, blue: 0.0902, opacity: 1),
            surfaceRaised: Color(.sRGB, red: 0.1020, green: 0.0941, blue: 0.1412, opacity: 1),
            border: Color(.sRGB, red: 0.1725, green: 0.1647, blue: 0.2196, opacity: 1),
            borderStrong: Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.3765, opacity: 1),
            content: Color(.sRGB, red: 0.9569, green: 0.9490, blue: 0.9843, opacity: 1),
            contentMuted: Color(.sRGB, red: 0.7765, green: 0.7608, blue: 0.8471, opacity: 1),
            contentFaint: Color(.sRGB, red: 0.5569, green: 0.5255, blue: 0.6706, opacity: 1),
            accent: Color(.sRGB, red: 0.3725, green: 0.8118, blue: 0.8118, opacity: 1),
            accentContent: Color(.sRGB, red: 0.0235, green: 0.1490, blue: 0.1569, opacity: 1),
            accentSoft: Color(.sRGB, red: 0.0667, green: 0.1725, blue: 0.1804, opacity: 1),
            signal: Color(.sRGB, red: 0.9098, green: 0.6392, blue: 0.2392, opacity: 1),
            signalSoft: Color(.sRGB, red: 0.1647, green: 0.1294, blue: 0.0784, opacity: 1),
            danger: Color(.sRGB, red: 0.9294, green: 0.4314, blue: 0.4549, opacity: 1),
            ok: Color(.sRGB, red: 0.4392, green: 0.8039, blue: 0.6706, opacity: 1),
            scrim: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.72)
        )
    )
}

/// One colour per person, indexed by the core's `peerColorIndex`.
enum ThemePeers {
    static let light: [Color] = [Color(.sRGB, red: 0.7020, green: 0.1490, blue: 0.1176, opacity: 1), Color(.sRGB, red: 0.4157, green: 0.2471, blue: 0.7843, opacity: 1), Color(.sRGB, red: 0.1765, green: 0.4784, blue: 0.2118, opacity: 1), Color(.sRGB, red: 0.0431, green: 0.4353, blue: 0.5255, opacity: 1), Color(.sRGB, red: 0.1373, green: 0.3373, blue: 0.7608, opacity: 1), Color(.sRGB, red: 0.6902, green: 0.1882, blue: 0.4314, opacity: 1), Color(.sRGB, red: 0.3333, green: 0.3216, blue: 0.4000, opacity: 1)]
    static let paper: [Color] = [Color(.sRGB, red: 0.7020, green: 0.1490, blue: 0.1176, opacity: 1), Color(.sRGB, red: 0.4157, green: 0.2471, blue: 0.7843, opacity: 1), Color(.sRGB, red: 0.1765, green: 0.4784, blue: 0.2118, opacity: 1), Color(.sRGB, red: 0.0431, green: 0.4353, blue: 0.5255, opacity: 1), Color(.sRGB, red: 0.1373, green: 0.3373, blue: 0.7608, opacity: 1), Color(.sRGB, red: 0.6902, green: 0.1882, blue: 0.4314, opacity: 1), Color(.sRGB, red: 0.3333, green: 0.3216, blue: 0.4000, opacity: 1)]
    static let dark: [Color] = [Color(.sRGB, red: 0.9490, green: 0.5451, blue: 0.5098, opacity: 1), Color(.sRGB, red: 0.7255, green: 0.6431, blue: 1.0000, opacity: 1), Color(.sRGB, red: 0.4980, green: 0.8235, blue: 0.5412, opacity: 1), Color(.sRGB, red: 0.4235, green: 0.8157, blue: 0.9020, opacity: 1), Color(.sRGB, red: 0.5412, green: 0.7059, blue: 1.0000, opacity: 1), Color(.sRGB, red: 0.9569, green: 0.5608, blue: 0.7529, opacity: 1), Color(.sRGB, red: 0.7176, green: 0.7059, blue: 0.7804, opacity: 1)]
    static let black: [Color] = [Color(.sRGB, red: 0.9490, green: 0.5451, blue: 0.5098, opacity: 1), Color(.sRGB, red: 0.7255, green: 0.6431, blue: 1.0000, opacity: 1), Color(.sRGB, red: 0.4980, green: 0.8235, blue: 0.5412, opacity: 1), Color(.sRGB, red: 0.4235, green: 0.8157, blue: 0.9020, opacity: 1), Color(.sRGB, red: 0.5412, green: 0.7059, blue: 1.0000, opacity: 1), Color(.sRGB, red: 0.9569, green: 0.5608, blue: 0.7529, opacity: 1), Color(.sRGB, red: 0.7176, green: 0.7059, blue: 0.7804, opacity: 1)]
}

/// The type ranks.
///
/// Every one is a text *style*, never a size. `Font.system(.body)`
/// scales with the reader's Dynamic Type setting; `Font.system(size:)`
/// does not, and the difference is invisible to whoever writes it.
enum ThemeType {
    static let label = Font.system(.caption2)
    static let meta = Font.system(.caption)
    static let ui = Font.system(.footnote)
    static let uiLg = Font.system(.subheadline)
    static let avatar = Font.system(.title2)
    static let body = Font.system(.body)
    static let longread = Font.system(.body, design: .serif)
    static let bodyOwn = Font.system(.body)
}

/// Radius, elevation and layout, in points.
///
/// The pane breakpoints are computed from the pane widths rather
/// than written down. RootView.swift's own threeColumnWidth is a
/// separate, hardcoded 1000 — see the design's open questions.
enum Metrics {
    static let radiusControl: CGFloat = 6
    static let radiusCard: CGFloat = 8
    static let radiusPill: CGFloat = .infinity
    static let radiusSharp: CGFloat = 0
    static let overlayShadowRadius: CGFloat = 12
    static let overlayShadowY: CGFloat = 4
    static let rosterWidth: CGFloat = 288
    static let panelWidth: CGFloat = 320
    static let sheetWidth: CGFloat = 630
    static let railWidth: CGFloat = 56
    static let panelColumn: CGFloat = 1238
    static let panelColumnWithRail: CGFloat = 1294
}
