"""Jetpack Compose emitter.

Colours only. Faces and text styles stay in Theme.kt, for the same reason
they stay in Theme.swift: emitting `sp` values here would ignore the
reader's font-size setting, and it would look like it had worked.
"""

import textwrap

from .contrast import parse_rgba
from .model import ROLES, Appearance, Tokens

HEADER = """\
// Generated by scripts/generate-tokens.py from design/tokens.toml.
// Do not edit — edit the source and regenerate. CI fails on drift.

package dev.supermessage

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
"""


def _camel(role: str) -> str:
    head, *rest = role.split("-")
    return head + "".join(part.capitalize() for part in rest)


def _argb(value: str) -> str:
    if value.startswith("rgb"):
        r, g, b, alpha = parse_rgba(value)
        a = round(alpha * 255)
    else:
        h = value.lstrip("#")
        r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
        a = 255
    return f"Color(0x{a:02X}{r:02X}{g:02X}{b:02X})"


def _doc(text: str, indent: str) -> str:
    if not text:
        return ""
    body = "\n".join(f"{indent} * {line}" for line in textwrap.wrap(text, 70))
    return f"{indent}/**\n{body}\n{indent} */\n"


def _palette(appearance: Appearance) -> str:
    lines = [f"    val {appearance.name} = SupermessageColorRoles(\n"]
    for role in ROLES:
        lines.append(f"        {_camel(role)} = {_argb(appearance.colors[role])},\n")
    lines.append("    )\n")
    return "".join(lines)


def emit_kotlin(tokens: Tokens) -> str:
    light = tokens.appearances["light"]
    members = "".join(
        _doc(light.comments.get(role, ""), "    ")
        + f"    val {_camel(role)}: Color,\n"
        for role in ROLES
    )
    return (
        HEADER
        + "\n/** The sixteen colour roles, one value each. */\n"
        + "@Immutable\n"
        + "data class SupermessageColorRoles(\n"
        + members
        + ")\n"
        + "\n/**\n"
        + " * The three appearances.\n"
        + " *\n"
        + ' * Android binds `paper` to light and `dark` to dark: paper is what\n'
        + ' * "light" means on a phone. There is no picker — see Theme.kt.\n'
        + " */\n"
        + "object GeneratedThemeTokens {\n"
        + _palette(tokens.appearances["light"])
        + "\n"
        + _palette(tokens.appearances["dark"])
        + "\n"
        + _palette(tokens.appearances["paper"])
        + "}\n"
    )
