"""SwiftUI emitter.

Colours only. The faces stay in Theme.swift because they are text *styles*
(`Font.system(.body, design: .serif)`), not sizes — emitting a point size
here would silently cost every iOS user Dynamic Type, and it would look
like it had worked.
"""

import textwrap

from .contrast import parse_rgba
from .model import ROLES, Appearance, Tokens

HEADER = """\
// Generated by scripts/generate-tokens.py from design/tokens.toml.
// Do not edit — edit the source and regenerate. CI fails on drift.

import SwiftUI
"""


def _camel(role: str) -> str:
    head, *rest = role.split("-")
    return head + "".join(part.capitalize() for part in rest)


def _literal(value: str) -> str:
    if value.startswith("rgb"):
        r, g, b, alpha = parse_rgba(value)
        opacity = f"{alpha:g}"
    else:
        h = value.lstrip("#")
        r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
        opacity = "1"
    return (
        f"Color(.sRGB, red: {r / 255:.4f}, green: {g / 255:.4f}, "
        f"blue: {b / 255:.4f}, opacity: {opacity})"
    )


def _doc(text: str, indent: str) -> str:
    if not text:
        return ""
    return "".join(
        f"{indent}/// {line}\n" for line in textwrap.wrap(text, width=72)
    )


def _palette(appearance: Appearance) -> str:
    lines = [f"    static let {appearance.name} = Palette(\n"]
    for index, role in enumerate(ROLES):
        comma = "," if index < len(ROLES) - 1 else ""
        lines.append(
            f"        {_camel(role)}: {_literal(appearance.colors[role])}{comma}\n"
        )
    lines.append("    )\n")
    return "".join(lines)


def emit_swift(tokens: Tokens) -> str:
    light = tokens.appearances["light"]
    members = "".join(
        _doc(light.comments.get(role, ""), "    ") + f"    let {_camel(role)}: Color\n"
        for role in ROLES
    )
    return (
        HEADER
        + "\n/// The sixteen colour roles, one value each.\n"
        + "struct Palette {\n"
        + members
        + "}\n"
        + "\n/// The three appearances.\n"
        + "///\n"
        + "/// iOS binds `paper` to light and `dark` to dark: paper is what\n"
        + '/// "light" means on a phone. There is no picker — see Theme.swift.\n'
        + "enum ThemeTokens {\n"
        + _palette(tokens.appearances["light"])
        + "\n"
        + _palette(tokens.appearances["dark"])
        + "\n"
        + _palette(tokens.appearances["paper"])
        + "}\n"
    )
