"""CSS emitters. Three targets share this module because they share a
syntax, not because they share a file.
"""

import textwrap

from .model import ROLES, Appearance, Tokens

HEADER = """\
/*
 * Generated by scripts/generate-tokens.py from design/tokens.toml.
 * Do not edit — edit the source and regenerate. CI fails on drift.
 */
"""


def _comment(text: str, indent: str) -> str:
    if not text:
        return ""
    wrapped = textwrap.wrap(text, width=max(32, 76 - len(indent)))
    body = "\n".join(f"{indent} * {line}" for line in wrapped)
    return f"{indent}/*\n{body}\n{indent} */\n"


def _block(appearance: Appearance, indent: str) -> str:
    out = []
    for role in ROLES:
        out.append(_comment(appearance.comments.get(role, ""), indent))
        out.append(f"{indent}--color-{role}: {appearance.colors[role]};\n")
    return "".join(out)


def emit_app_css(tokens: Tokens) -> str:
    """The desktop app.

    Light sits on bare `:root` via Tailwind's `@theme`, and the other two
    appearances redefine it. No colour is ever defined only inside a media
    query — a role whose sole definition lives in the dark block leaves the
    light theme with nothing at all.
    """
    return (
        HEADER
        + "\n@theme {\n"
        + _block(tokens.appearances["light"], "  ")
        + "}\n"
        + "\n@layer theme {\n"
        + "  @media (prefers-color-scheme: dark) {\n"
        + "    :root {\n"
        + _block(tokens.appearances["dark"], "      ")
        + "    }\n"
        + "  }\n"
        + "\n"
        + '  /*\n   * Paper is what "light" means on a phone. Nothing selects it on\n'
        + "   * desktop; the binding lives in each native theme.\n   */\n"
        + '  [data-appearance="paper"] {\n'
        + _block(tokens.appearances["paper"], "    ")
        + "  }\n"
        + "}\n"
    )
