"""SwiftUI emitter.

Colours only. The faces stay in Theme.swift because they are text *styles*
(`Font.system(.body, design: .serif)`), not sizes — emitting a point size
here would silently cost every iOS user Dynamic Type, and it would look
like it had worked.
"""

import textwrap

from .contrast import parse_rgba
from .model import ROLES, TYPE_ROLES, Appearance, Tokens

#: A family becomes a *design*, never a face name. The system
#: resolves .serif to New York and .monospaced to SF Mono, which is
#: what keeps Dynamic Type working and keeps nothing bundled.
DESIGNS = {"sans": "", "serif": ", design: .serif", "mono": ", design: .monospaced"}

HEADER = """\
// Generated by scripts/generate-tokens.py from design/tokens.toml.
// Do not edit — edit the source and regenerate. CI fails on drift.

import SwiftUI
"""


def _camel(role: str) -> str:
    head, *rest = role.split("-")
    return head + "".join(part.capitalize() for part in rest)


def _literal(value: str) -> str:
    if value.startswith("rgb"):
        r, g, b, alpha = parse_rgba(value)
        opacity = f"{alpha:g}"
    else:
        h = value.lstrip("#")
        r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
        opacity = "1"
    return (
        f"Color(.sRGB, red: {r / 255:.4f}, green: {g / 255:.4f}, "
        f"blue: {b / 255:.4f}, opacity: {opacity})"
    )


def _doc(text: str, indent: str) -> str:
    if not text:
        return ""
    return "".join(
        f"{indent}/// {line}\n" for line in textwrap.wrap(text, width=72)
    )


def _palette(appearance: Appearance) -> str:
    lines = [f"    static let {appearance.name} = Palette(\n"]
    for index, role in enumerate(ROLES):
        comma = "," if index < len(ROLES) - 1 else ""
        lines.append(
            f"        {_camel(role)}: {_literal(appearance.colors[role])}{comma}\n"
        )
    lines.append("    )\n")
    return "".join(lines)


def _type_block(tokens: Tokens) -> str:
    lines = [
        "\n/// The type ranks.\n",
        "///\n",
        "/// Every one is a text *style*, never a size. `Font.system(.body)`\n",
        "/// scales with the reader's Dynamic Type setting; `Font.system(size:)`\n",
        "/// does not, and the difference is invisible to whoever writes it.\n",
        "enum ThemeType {\n",
    ]
    for name in TYPE_ROLES:
        role = tokens.type[name]
        head, *rest = name.split("-")
        camel = head + "".join(part.capitalize() for part in rest)
        lines.append(
            f"    static let {camel} = "
            f"Font.system(.{role.ios}{DESIGNS[role.family]})\n"
        )
    lines.append("}\n")
    return "".join(lines)


def _metrics_block(tokens: Tokens) -> str:
    radius = tokens.scale["radius"]
    overlay = tokens.scale["elevation"]["overlay"]["ios"]
    layout = tokens.scale["layout"]
    lines = [
        "\n/// Radius, elevation and layout, in points.\n",
        "///\n",
        "/// The pane breakpoints are computed from the pane widths rather\n",
        "/// than written down. RootView.swift's own threeColumnWidth is a\n",
        "/// separate, hardcoded 1000 — see the design's open questions.\n",
        "enum Metrics {\n",
    ]
    for name, value in radius.items():
        points = "0" if value == "0" else value.replace("px", "")
        if name == "pill":
            lines.append(f"    static let radius{name.capitalize()}: CGFloat = .infinity\n")
        else:
            lines.append(f"    static let radius{name.capitalize()}: CGFloat = {points}\n")
    lines.append(
        f"    static let overlayShadowRadius: CGFloat = {overlay['radius']}\n"
        f"    static let overlayShadowY: CGFloat = {overlay['y']}\n"
    )
    for name, value in layout.items():
        lines.append(f"    static let {name}Width: CGFloat = {value}\n")
    for name, value in tokens.breakpoints.items():
        head, *rest = name.split("-")
        camel = head + "".join(part.capitalize() for part in rest)
        lines.append(f"    static let {camel}: CGFloat = {value}\n")
    lines.append("}\n")
    return "".join(lines)


def _accents_block(tokens: Tokens) -> str:
    if not tokens.accents:
        return ""
    names = sorted(tokens.accents)
    lines = [
        "\n/// One accent, in every appearance: the whole palette with the accent\n",
        "/// applied — its own accent roles, and grounds and greys in its hue.\n",
        "struct AccentSet {\n",
    ]
    for appearance in tokens.appearances:
        lines.append(f"    let {appearance}: Palette\n")
    lines += [
        "}\n",
        "\n/// The accents a reader may choose. Violet, the default, is the\n",
        "/// appearances' own and is not listed.\n",
        "enum ThemeAccents {\n",
        f"    static let names = [{', '.join(repr(n).replace(chr(39), chr(34)) for n in names)}]\n",
    ]
    for name in names:
        lines.append(f"    static let {name} = AccentSet(\n")
        apps = list(tokens.appearances)
        for i, appearance in enumerate(apps):
            palette = tokens.accent_palette(name, appearance)
            comma = "," if i < len(apps) - 1 else ""
            lines.append(f"        {appearance}: Palette(\n")
            for j, role in enumerate(ROLES):
                sep = "," if j < len(ROLES) - 1 else ""
                lines.append(f"            {_camel(role)}: {_literal(palette[role])}{sep}\n")
            lines.append(f"        ){comma}\n")
        lines.append("    )\n")
    lines.append("}\n")
    return "".join(lines)


def _peers_block(tokens: Tokens) -> str:
    if not tokens.peers:
        return ""
    lines = [
        "\n/// One colour per person, indexed by the core's `peerColorIndex`.\n",
        "enum ThemePeers {\n",
    ]
    for appearance, values in tokens.peers.items():
        items = ", ".join(_literal(v) for v in values)
        lines.append(f"    static let {appearance}: [Color] = [{items}]\n")
    lines.append("}\n")
    return "".join(lines)


def emit_swift(tokens: Tokens) -> str:
    light = tokens.appearances["light"]
    members = "".join(
        _doc(light.comments.get(role, ""), "    ") + f"    let {_camel(role)}: Color\n"
        for role in ROLES
    )
    return (
        HEADER
        + "\n/// The sixteen colour roles, one value each.\n"
        + "struct Palette {\n"
        + members
        + "}\n"
        + "\n/// The appearances.\n"
        + "///\n"
        + "/// iOS binds `paper` to light and `dark` (or `black`, the reader's\n"
        + "/// choice) to dark — see Theme.swift.\n"
        + "enum ThemeTokens {\n"
        + "\n".join(_palette(a) for a in tokens.appearances.values())
        + "}\n"
        + _accents_block(tokens)
        + _peers_block(tokens)
        + _type_block(tokens)
        + _metrics_block(tokens)
    )
