"""The mark, emitted: the logo SVG, and Android's launcher-icon resources.

The geometry lives here and the colours live in design/tokens.toml, so the
mark is a generated file like any other and CI's drift check covers every
copy of it. Before this, `assets/logo.svg` had four copies' worth of
disagreement around it: the iOS icon used it, the favicons were a third
design in colours outside the palette, the desktop app wore Tauri's default
icon and the Svelte logo, and Android had no launcher icon at all.

The mark is *drawn*, not traced. The artwork it came from is a 420px raster
whose bubble edges are soft gradients rather than outlines, so tracing it
reproduced the JPEG's noise at every size. Both bubbles measure as ellipses
to within a pixel or two, so here they are ellipses, and each tail is a cubic
that leaves and re-enters its ellipse's edge.

Raster icons (the iOS AppIcon, the desktop icon set) cannot be rendered on a
CI runner with nothing but Python, so `assets/build-icon.py` renders those
from the SVG this writes.
"""

from .model import Tokens

#: The mark's own box: `viewBox="0 {VIEW_Y} {VIEW_W} {VIEW_H}"`.
#:
#: The drawing spans x 9–381 and y 20–343.2, and the box is that plus an even
#: margin. It was 0 0 390 340, which sheared 3px off the coral tail's tip in
#: every rendering that honoured the viewBox — invisible in the iOS icon, which
#: never used it, and a flat-bottomed tail on every favicon.
VIEW_Y, VIEW_W, VIEW_H = 10, 390, 344

# Measured off the source artwork.
BLUE = dict(cx=140.0, cy=124.0, rx=131.0, ry=104.0)
CORAL = dict(cx=257.5, cy=196.5, rx=123.5, ry=97.5)
BLUE_TAIL = (
    "M 78 200 C 66 226 52 236 42 252 C 30 272 56 282 82 270 "
    "C 118 254 152 230 176 208 Z"
)
CORAL_TAIL = (
    "M 316 270 C 330 294 344 304 354 320 C 366 340 340 350 314 338 "
    "C 278 322 244 298 220 276 Z"
)

#: Each gradient's axis, in the mark's own coordinates. One axis per shape,
#: shared by its body and tail — see the comment in the SVG.
AXES = {
    "blue": (9, 20, 271, 264),
    "coral": (134, 99, 381, 329),
    "overlap": (134, 99, 271, 264),
}

GENERATED_XML = (
    "<!-- Generated by scripts/generate-tokens.py from design/tokens.toml.\n"
    "     Do not edit — edit the source and regenerate. CI fails on drift. -->\n"
)


def _id(shape: str) -> str:
    return "sm" + shape.capitalize()


def emit_logo_svg(tokens: Tokens) -> str:
    mark = tokens.brand.mark
    defs = "\n".join(
        f'    <linearGradient id="{_id(shape)}" gradientUnits="userSpaceOnUse" '
        f'x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}">\n'
        f'      <stop offset="0" stop-color="{mark[shape][0]}"/>\n'
        f'      <stop offset="1" stop-color="{mark[shape][1]}"/>\n'
        f"    </linearGradient>"
        for shape, (x1, y1, x2, y2) in AXES.items()
    )

    def bubble(e: dict, tail: str, fill: str) -> str:
        return (
            f'  <ellipse cx="{e["cx"]}" cy="{e["cy"]}" rx="{e["rx"]}" '
            f'ry="{e["ry"]}" fill="{fill}"/>\n'
            f'  <path d="{tail}" fill="{fill}"/>'
        )

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 {VIEW_Y} {VIEW_W} {VIEW_H}" width="{VIEW_W}" height="{VIEW_H}" role="img" aria-label="supermessage">
  <title>supermessage</title>
  <desc>Two overlapping speech bubbles.</desc>
  <!--
    Generated by scripts/generate-tokens.py from design/tokens.toml. Do not
    edit — edit the source and regenerate. CI fails on drift.

    Body and tail are two shapes sharing one `userSpaceOnUse` gradient, which
    is what makes them read as a single object: an `objectBoundingBox`
    gradient would restart at each shape and the seam would show.
  -->
  <defs>
{defs}
    <clipPath id="smCoralShape">
      <ellipse cx="{CORAL['cx']}" cy="{CORAL['cy']}" rx="{CORAL['rx']}" ry="{CORAL['ry']}"/>
      <path d="{CORAL_TAIL}"/>
    </clipPath>
  </defs>
{bubble(BLUE, BLUE_TAIL, "url(#smBlue)")}
{bubble(CORAL, CORAL_TAIL, "url(#smCoral)")}
  <!--
    Where they cross. Not a third traced shape: the blue bubble clipped to the
    coral one is the same region bounded by the two real curves, so every edge
    in the mark belongs to one of the two bubbles.
  -->
  <g clip-path="url(#smCoralShape)">
{bubble(BLUE, BLUE_TAIL, "url(#smOverlap)")}
  </g>
</svg>
"""


# ── Android ──────────────────────────────────────────────────────────────────
#
# An adaptive icon is a 108dp square of which only the central 66dp circle is
# guaranteed to survive the launcher's mask. The mark is scaled so its
# furthest point — the coral tail's tip — stays inside that circle.

ADAPTIVE = 108
SCALE = 0.135
OFFSET_X = (ADAPTIVE - VIEW_W * SCALE) / 2
OFFSET_Y = (ADAPTIVE - VIEW_H * SCALE) / 2 - VIEW_Y * SCALE


def _ellipse_path(e: dict) -> str:
    """An ellipse as two arcs: VectorDrawable has no <ellipse>."""
    left = e["cx"] - e["rx"]
    return (
        f"M {left:g} {e['cy']:g} "
        f"a {e['rx']:g} {e['ry']:g} 0 1 0 {2 * e['rx']:g} 0 "
        f"a {e['rx']:g} {e['ry']:g} 0 1 0 {-2 * e['rx']:g} 0 Z"
    )


def _gradient_path(path: str, shape: str) -> str:
    x1, y1, x2, y2 = AXES[shape]
    return (
        f'        <path android:pathData="{path}">\n'
        f'            <aapt:attr name="android:fillColor">\n'
        f'                <gradient\n'
        f'                    android:type="linear"\n'
        f'                    android:startX="{x1}" android:startY="{y1}"\n'
        f'                    android:endX="{x2}" android:endY="{y2}"\n'
        f'                    android:startColor="@color/sm_mark_{shape}_from"\n'
        f'                    android:endColor="@color/sm_mark_{shape}_to" />\n'
        f"            </aapt:attr>\n"
        f"        </path>\n"
    )


def _vector(body: str, extra_ns: str = "") -> str:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        + GENERATED_XML
        + f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra_ns}\n'
        f'    android:width="{ADAPTIVE}dp"\n'
        f'    android:height="{ADAPTIVE}dp"\n'
        f'    android:viewportWidth="{ADAPTIVE}"\n'
        f'    android:viewportHeight="{ADAPTIVE}">\n'
        f'    <group\n'
        f'        android:translateX="{OFFSET_X:g}"\n'
        f'        android:translateY="{OFFSET_Y:g}"\n'
        f'        android:scaleX="{SCALE:g}"\n'
        f'        android:scaleY="{SCALE:g}">\n'
        + body
        + "    </group>\n"
        "</vector>\n"
    )


def emit_android_foreground(tokens: Tokens) -> str:
    blue, coral = _ellipse_path(BLUE), _ellipse_path(CORAL)
    body = (
        _gradient_path(blue, "blue")
        + _gradient_path(BLUE_TAIL, "blue")
        + _gradient_path(coral, "coral")
        + _gradient_path(CORAL_TAIL, "coral")
    )
    # The crossing, once per coral shape. SVG unions a <clipPath>'s children;
    # a single VectorDrawable <clip-path> holding both would instead fill by
    # winding rule, and whether the join survived would depend on which way
    # each path happens to run. Two clipped groups draw the overlap twice
    # where they coincide, in the same opaque colour, which is invisible.
    for clip in (coral, CORAL_TAIL):
        body += (
            "        <group>\n"
            f'            <clip-path android:pathData="{clip}" />\n'
            + _gradient_path(blue, "overlap")
            + _gradient_path(BLUE_TAIL, "overlap")
            + "        </group>\n"
        )
    return _vector(body, '\n    xmlns:aapt="http://schemas.android.com/aapt"')


def emit_android_monochrome(tokens: Tokens) -> str:
    """The themed-icon layer: an alpha mask the launcher tints itself.

    Colour carries nothing here, so the crossing is told by opacity instead:
    the coral bubble over the blue one composites to a third, denser value
    where they overlap, the way the full-colour mark shows a third colour.
    """
    blue, coral = _ellipse_path(BLUE), _ellipse_path(CORAL)
    body = "".join(
        f'        <path android:pathData="{path}" android:fillColor="#FFFFFFFF" '
        f'android:fillAlpha="{alpha}" />\n'
        for path, alpha in (
            (blue, "0.5"),
            (BLUE_TAIL, "0.5"),
            (coral, "0.75"),
            (CORAL_TAIL, "0.75"),
        )
    )
    return _vector(body)


def emit_android_colors(tokens: Tokens) -> str:
    """Colour resources for the few things Compose cannot paint.

    The window background before the first frame and the launcher icon are
    both drawn by the system from resources, and resource XML cannot read a
    Kotlin `Color`. So they read these, which come from the same source as
    GeneratedThemeTokens.kt — instead of a hex kept "in sync by hand", which
    is how the window went on showing a retired palette's grounds.

    Only `paper` and `dark` are emitted: those are the two Android binds.
    """
    lines = ['<?xml version="1.0" encoding="utf-8"?>\n', GENERATED_XML, "<resources>\n"]
    for name in ("paper", "dark"):
        appearance = tokens.appearances[name]
        for role, value in appearance.colors.items():
            if not value.startswith("#"):
                # The scrim is rgb() with alpha; nothing drawn from
                # resources needs it.
                continue
            key = role.replace("-", "_")
            lines.append(
                f'    <color name="sm_{name}_{key}">{value.upper()}</color>\n'
            )
    for ground, value in tokens.brand.ground.items():
        lines.append(f'    <color name="sm_ground_{ground}">{value.upper()}</color>\n')
    for shape, (start, end) in tokens.brand.mark.items():
        lines.append(f'    <color name="sm_mark_{shape}_from">{start.upper()}</color>\n')
        lines.append(f'    <color name="sm_mark_{shape}_to">{end.upper()}</color>\n')
    lines.append("</resources>\n")
    return "".join(lines)
