"""CSS emitters. Three targets share this module because they share a
syntax, not because they share a file.
"""

import textwrap

from .model import ROLES, TYPE_ROLES, Appearance, Tokens

FAMILY_STACKS = {
    "sans": '"IBM Plex Sans Variable", var(--font-system)',
    "serif": '"Source Serif 4 Variable", Georgia, serif',
    "mono": '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
}

SYSTEM_STACK = (
    "-apple-system, BlinkMacSystemFont, \"Segoe UI Variable Text\", "
    "\"Segoe UI\", Roboto, Cantarell, \"Noto Sans\", Ubuntu, sans-serif"
)

HEADER = """\
/*
 * Generated by scripts/generate-tokens.py from design/tokens.toml.
 * Do not edit — edit the source and regenerate. CI fails on drift.
 */
"""


def _comment(text: str, indent: str) -> str:
    if not text:
        return ""
    wrapped = textwrap.wrap(text, width=max(32, 76 - len(indent)))
    body = "\n".join(f"{indent} * {line}" for line in wrapped)
    return f"{indent}/*\n{body}\n{indent} */\n"


def _block(appearance: Appearance, indent: str) -> str:
    out = []
    for role in ROLES:
        out.append(_comment(appearance.comments.get(role, ""), indent))
        out.append(f"{indent}--color-{role}: {appearance.colors[role]};\n")
    return "".join(out)


def _type_block(tokens: Tokens, indent: str) -> str:
    """The type scale, as Tailwind v4 theme keys.

    Letter-spacing and weight ride as `--text-<role>--*` sub-properties so a
    call site only has to name the family and, for the label rank,
    `uppercase` — Tailwind has no text-transform convention.
    """
    out = [
        f"\n{indent}/* System stack. On iOS, -apple-system also carries Dynamic Type. */\n",
        f'{indent}--font-system: {SYSTEM_STACK};\n',
    ]
    for family, stack in FAMILY_STACKS.items():
        out.append(f"{indent}--font-{family}: {stack};\n")

    out.append(
        f"\n{indent}/* Type scale. Bundled faces, because the app's CSP is\n"
        f"{indent} * default-src 'self' and nothing may be fetched from a CDN. */\n"
    )
    for name in TYPE_ROLES:
        role = tokens.type[name]
        web = role.web
        out.append(f"{indent}--text-{name}: {web['size']};\n")
        if "line_height" in web:
            out.append(f"{indent}--text-{name}--line-height: {web['line_height']};\n")
        if "weight" in web:
            out.append(f"{indent}--text-{name}--font-weight: {web['weight']};\n")
        if "letter_spacing" in web:
            out.append(
                f"{indent}--text-{name}--letter-spacing: {web['letter_spacing']};\n"
            )
    return "".join(out)


def _scale_block(tokens: Tokens, indent: str) -> str:
    """Radius, elevation, motion, and the layout constants.

    The breakpoints are emitted as values *computed* from the pane widths
    above them, not as literals. That is the whole reason they are here:
    `+page.svelte` used to carry `1238` ten times over a comment explaining
    how it was derived.
    """
    out = [
        f"\n{indent}/* Radius, named by role. `rounded-md` cannot be wrong because\n"
        f"{indent} * it says nothing; `rounded-control` can. */\n"
    ]
    for name, value in tokens.scale["radius"].items():
        out.append(f"{indent}--radius-{name}: {value};\n")

    out.append(
        f"\n{indent}/* Depth is the surface ramp plus a hairline. Shadow means one\n"
        f"{indent} * thing only: floating over the scrim. */\n"
        f'{indent}--shadow-overlay: {tokens.scale["elevation"]["overlay"]["web"]};\n'
    )

    motion = tokens.scale["motion"]
    out.append(
        f"\n{indent}/* Almost none, deliberately — but nameable, so anything added\n"
        f"{indent} * is inside a budget. */\n"
        f'{indent}--duration-quick: {motion["quick"]};\n'
        f'{indent}--duration-settle: {motion["settle"]};\n'
        f'{indent}--ease-standard: {motion["easing"]};\n'
    )

    out.append(f"\n{indent}/* Pane widths, and the breakpoints derived from them. */\n")
    for name, value in tokens.scale["layout"].items():
        out.append(f"{indent}--layout-{name}: {value}px;\n")
    for name, value in tokens.breakpoints.items():
        out.append(f"{indent}--breakpoint-{name}: {value}px;\n")
    return "".join(out)


def _peer_block(tokens: Tokens, appearance: str, indent: str) -> str:
    """`--color-peer-0` … `-6`: one colour per person, indexed by the core."""
    return "".join(
        f"{indent}--color-peer-{i}: {value};\n"
        for i, value in enumerate(tokens.peers.get(appearance, []))
    )


def _accent_vars(tokens: Tokens, accent: str, appearance: str, indent: str) -> str:
    roles = tokens.accents[accent][appearance]
    return "".join(f"{indent}--color-{role}: {roles[role]};\n" for role in roles)


def _accent_blocks(tokens: Tokens) -> str:
    """A chosen accent, on top of whichever appearance is in force.

    Emitted after the appearance blocks and with one more attribute in each
    selector, so it wins on specificity rather than on order: the bare
    `[data-accent]` for light, the OS's dark under the media query, and
    each explicit appearance.
    """
    out = []
    for name in sorted(tokens.accents):
        out.append(f'  :root[data-accent="{name}"] {{\n')
        out.append(_accent_vars(tokens, name, "light", "    "))
        out.append("  }\n")
        out.append("  @media (prefers-color-scheme: dark) {\n")
        out.append(f'    :root[data-accent="{name}"]:not([data-appearance]) {{\n')
        out.append(_accent_vars(tokens, name, "dark", "      "))
        out.append("    }\n  }\n")
        for appearance in tokens.appearances:
            out.append(f'  [data-appearance="{appearance}"][data-accent="{name}"] {{\n')
            out.append(_accent_vars(tokens, name, appearance, "    "))
            out.append("  }\n")
    return "".join(out)


def emit_app_css(tokens: Tokens) -> str:
    """The desktop app.

    Light sits on bare `:root` via Tailwind's `@theme`, and the other two
    appearances redefine it. No colour is ever defined only inside a media
    query — a role whose sole definition lives in the dark block leaves the
    light theme with nothing at all.
    """
    return (
        HEADER
        + "\n@theme {\n"
        + _block(tokens.appearances["light"], "  ")
        + _peer_block(tokens, "light", "  ")
        + _type_block(tokens, "  ")
        + _scale_block(tokens, "  ")
        + "}\n"
        + "\n@layer theme {\n"
        + "  /*\n"
        + "   * The OS's choice, but only when nothing has been chosen\n"
        + "   * explicitly.\n"
        + "   *\n"
        + "   * The :not() guard is belt-and-braces, not load-bearing: an\n"
        + "   * attribute selector and :root have the same specificity\n"
        + "   * (0,1,0), and the explicit blocks below are emitted after this\n"
        + "   * one, so source order already gives them precedence. Measured:\n"
        + "   * removing the guard changes nothing in a dark-set browser.\n"
        + "   *\n"
        + "   * It is kept because it makes that precedence independent of\n"
        + "   * emission order — reorder the blocks below and the behaviour\n"
        + "   * survives. The order is what the test asserts.\n"
        + "   */\n"
        + "  @media (prefers-color-scheme: dark) {\n"
        + "    :root:not([data-appearance]) {\n"
        + _block(tokens.appearances["dark"], "      ")
        + _peer_block(tokens, "dark", "      ")
        + "    }\n"
        + "  }\n"
        + "\n"
        + "  /*\n"
        + "   * An explicit choice, in all three directions.\n"
        + "   *\n"
        + '   * `paper` is what "light" means on a phone, and nothing selects\n'
        + "   * it on desktop — the binding lives in each native theme. The\n"
        + "   * other two exist so a story catalogue, and later a user\n"
        + "   * preference, can override the OS either way. A catalogue that\n"
        + "   * cannot switch appearances cannot do the job it exists for.\n"
        + "   */\n"
        + "".join(
            f'  [data-appearance="{name}"] {{\n'
            + _block(tokens.appearances[name], "    ")
            + _peer_block(tokens, name, "    ")
            + "  }\n"
            for name in tokens.appearances
        )
        + _accent_blocks(tokens)
        + "}\n"
    )


def emit_landing_css(tokens: Tokens) -> str:
    """The landing page.

    Dark is its default rather than the OS's choice: it is a single
    marketing page and it commits to one look. Light is kept for a visitor
    whose system asks for it.
    """
    return (
        HEADER
        + "\n:root {\n"
        + _block(tokens.appearances["dark"], "  ")
        + "}\n"
        + "\n@media (prefers-color-scheme: light) {\n"
        + "  :root {\n"
        + _block(tokens.appearances["light"], "    ")
        + "  }\n"
        + "}\n"
    )


def emit_docs_css(tokens: Tokens) -> str:
    """The docs site.

    `html:root` rather than `:root`, and it is load-bearing. Astro bundled
    this file BEFORE Starlight's own props.css, so at equal specificity
    Starlight's defaults won and every value here did nothing — with a build
    that succeeded and a page that looked untouched. `html:root` is (0,0,1,1)
    against `:root`'s (0,0,1,0), so the override holds whatever order the
    bundler picks.

    Both themes are kept deliberately. Documentation is read at a desk in
    daylight and in bed at midnight, and a docs site that ignores the
    reader's preference is choosing a mood over legibility.
    """
    return (
        HEADER
        + "\nhtml:root {\n"
        + _block(tokens.appearances["dark"], "  ")
        + "}\n"
        + "\nhtml:root[data-theme='light'] {\n"
        + _block(tokens.appearances["light"], "  ")
        + "}\n"
    )
