import re
import unittest
from pathlib import Path

from scripts.tokens.emit_css import emit_app_css
from scripts.tokens.model import ROLES, load

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "design" / "tokens.toml"
GOLDEN = Path(__file__).parent / "golden"


def code_only(source: str) -> str:
    """Strip comments, so a guard inspects code rather than prose.

    These emitters document the traps they avoid — the Swift says
    "Font.system(size:) does not scale", the Kotlin says "a hardcoded .sp
    would ignore it". A naive `assertNotIn` then fires on the explanation
    and not on any real defect, which is how a guard ends up being deleted
    for crying wolf.
    """
    out, in_block = [], False
    for line in source.splitlines():
        stripped = line.strip()
        if in_block:
            if "*/" in stripped:
                in_block = False
            continue
        if stripped.startswith("/*"):
            in_block = "*/" not in stripped
            continue
        if stripped.startswith("//") or stripped.startswith("*"):
            continue
        out.append(line)
    return "\n".join(out)



class AppCssTests(unittest.TestCase):
    def setUp(self):
        self.css = emit_app_css(load(SOURCE))
        self.root = self.css.split("@layer theme")[0]

    def test_it_says_it_is_generated(self):
        self.assertIn("Generated by scripts/generate-tokens.py", self.css)
        self.assertIn("do not edit", self.css.lower())

    def test_light_is_the_bare_root_and_defines_every_role(self):
        for role in ROLES:
            with self.subTest(role=role):
                self.assertIn(f"--color-{role}:", self.root)

    def test_no_colour_is_defined_only_inside_a_media_query(self):
        """A colour whose only definition is in the dark block leaves the
        light theme with nothing. This is the rule app.css already follows
        and the one a generator can enforce for free."""
        declared_anywhere = set(re.findall(r"--color-([a-z-]+):", self.css))
        declared_in_root = set(re.findall(r"--color-([a-z-]+):", self.root))
        self.assertEqual(declared_anywhere - declared_in_root, set())

    def test_dark_is_a_prefers_color_scheme_block(self):
        self.assertIn("@media (prefers-color-scheme: dark)", self.css)

    def test_paper_is_an_attribute_selector_not_the_default(self):
        self.assertIn('[data-appearance="paper"]', self.css)
        self.assertNotIn("#faf8f3", self.root)

    def test_every_appearances_values_actually_reach_the_output(self):
        tokens = load(SOURCE)
        for name, appearance in tokens.appearances.items():
            with self.subTest(appearance=name):
                self.assertIn(appearance.colors["surface"], self.css)
                self.assertIn(appearance.colors["signal"], self.css)

    def test_rationale_reaches_the_output(self):
        self.assertIn("2.92", self.css)

    def test_it_matches_the_golden_file(self):
        self.assertEqual(self.css, (GOLDEN / "app-tokens.css").read_text())



class SwiftTests(unittest.TestCase):
    def setUp(self):
        from scripts.tokens.emit_swift import emit_swift

        self.swift = emit_swift(load(SOURCE))

    def test_it_says_it_is_generated(self):
        self.assertIn("Generated by scripts/generate-tokens.py", self.swift)

    def test_all_three_palettes_exist(self):
        for name in ("light", "dark", "paper"):
            with self.subTest(name=name):
                self.assertIn(f"static let {name} = Palette(", self.swift)

    def test_roles_are_lower_camel_case(self):
        self.assertIn("surfaceSunken", self.swift)
        self.assertNotIn("surface-sunken:", self.swift)

    def test_no_fixed_point_sizes_leak_in(self):
        # Dynamic Type is the thing a naive generator destroys here. iOS
        # gets text scaling free because Theme.swift asks for a text
        # STYLE; emitting a size would silently take it away.
        code = code_only(self.swift)
        self.assertNotIn("Font.system(size:", code)
        self.assertNotIn(".font(.system(size:", code)

    def test_the_scrim_carries_its_alpha(self):
        self.assertIn("opacity: 0.45", self.swift)
        self.assertIn("opacity: 0.7", self.swift)

    def test_opaque_roles_are_fully_opaque(self):
        self.assertEqual(self.swift.count("opacity: 1"), 15 * 3)

    def test_it_matches_the_golden_file(self):
        self.assertEqual(
            self.swift, (GOLDEN / "ThemeTokens.swift").read_text()
        )

class KotlinTests(unittest.TestCase):
    def setUp(self):
        from scripts.tokens.emit_kotlin import emit_kotlin

        self.kt = emit_kotlin(load(SOURCE))

    def test_it_says_it_is_generated(self):
        self.assertIn("Generated by scripts/generate-tokens.py", self.kt)

    def test_all_three_palettes_exist(self):
        for name in ("light", "dark", "paper"):
            with self.subTest(name=name):
                self.assertIn(f"val {name} = SupermessageColorRoles(", self.kt)

    def test_colours_are_argb_longs(self):
        self.assertIn("Color(0xFFFDFCFF)", self.kt)

    def test_the_scrim_carries_its_alpha_in_the_argb(self):
        """A scrim emitted at 0xFF is opaque and hides the roster instead of
        veiling it, which is the whole failure this token exists to avoid.

        0.45 -> 0x73. 0.70 -> 0xB2, not 0xB3: 0.70 * 255 is exactly 178.5
        and Python rounds half to even. Either half is defensible (178/255
        is 0.698, 179/255 is 0.702) and the difference is invisible — but
        the value is pinned so a change to the rounding shows up as a
        failing test rather than as a silently different wash.
        """
        self.assertIn("Color(0x73221C38)", self.kt)
        self.assertIn("Color(0xB2151129)", self.kt)

    def test_no_sp_sizes_leak_in(self):
        # Android's equivalent of the Dynamic Type trap: a hardcoded sp
        # value ignores the reader's font-size setting.
        self.assertNotIn(".sp", code_only(self.kt))

    def test_role_names_match_the_swift_emitter(self):
        """The clearLayers/clearFullLayers bug, pinned.

        Two emitters naming the same role differently is not a compile
        error on either platform — it just means the two apps disagree
        about what a token is called, which is where this whole project
        started.
        """
        from scripts.tokens.emit_swift import emit_swift

        swift = emit_swift(load(SOURCE))
        for role in ROLES:
            head, *rest = role.split("-")
            camel = head + "".join(p.capitalize() for p in rest)
            with self.subTest(role=role):
                self.assertIn(camel, self.kt)
                self.assertIn(camel, swift)

    def test_it_matches_the_golden_file(self):
        self.assertEqual(
            self.kt, (GOLDEN / "GeneratedThemeTokens.kt").read_text()
        )

class MarketingTests(unittest.TestCase):
    def setUp(self):
        from scripts.tokens.emit_css import emit_docs_css, emit_landing_css

        self.landing = emit_landing_css(load(SOURCE))
        self.docs = emit_docs_css(load(SOURCE))

    def test_landing_uses_the_same_role_names_as_the_app(self):
        for role in ROLES:
            with self.subTest(role=role):
                self.assertIn(f"--color-{role}:", self.landing)

    def test_landing_no_longer_invents_its_own_names(self):
        """Two names for one thing is how the product and the site were free
        to drift. --ink, --violet and --amber are gone."""
        for legacy in ("--ink:", "--violet:", "--amber:", "--raised:", "--line:"):
            with self.subTest(legacy=legacy):
                self.assertNotIn(legacy, self.landing)

    def test_docs_uses_html_root_for_specificity(self):
        """Astro bundles this file before Starlight's props.css, so at equal
        specificity every value here would do nothing — with a build that
        succeeds and a page that looks untouched. html:root is (0,0,1,1)
        against Starlight's (0,0,1,0)."""
        self.assertIn("html:root {", self.docs)
        self.assertNotIn("\n:root {", self.docs)

    def test_the_three_marketing_literals_survive(self):
        # The whole reason the product adopted this hue.
        for literal in ("#151129", "#9d8ff0", "#e8a33d"):
            with self.subTest(literal=literal):
                self.assertIn(literal, self.landing)
                self.assertIn(literal, self.docs)

    def test_dark_is_the_default_on_the_marketing_surfaces(self):
        # The landing page commits to a dark look; the app follows the OS.
        first_block = self.landing.split("@media")[0]
        self.assertIn("#151129", first_block)
        self.assertNotIn("#fdfcff", first_block)

    def test_landing_matches_the_golden_file(self):
        self.assertEqual(
            self.landing, (GOLDEN / "landing-tokens.css").read_text()
        )

    def test_docs_matches_the_golden_file(self):
        self.assertEqual(self.docs, (GOLDEN / "docs-tokens.css").read_text())

class TypeEmissionTests(unittest.TestCase):
    """The Dynamic Type trap, guarded on both native platforms."""

    def test_css_emits_the_scale_with_its_sub_properties(self):
        css = emit_app_css(load(SOURCE))
        self.assertIn("--text-body: 0.9375rem", css)
        self.assertIn("--text-body--line-height: 1.62", css)
        self.assertIn("--text-label--letter-spacing: 0.08em", css)

    def test_css_emits_the_three_families(self):
        css = emit_app_css(load(SOURCE))
        for family in ("--font-sans:", "--font-serif:", "--font-mono:"):
            with self.subTest(family=family):
                self.assertIn(family, css)

    def test_swift_emits_text_styles_not_sizes(self):
        from scripts.tokens.emit_swift import emit_swift

        swift = emit_swift(load(SOURCE))
        self.assertIn("Font.system(.body, design: .serif)", swift)
        self.assertIn("Font.system(.footnote)", swift)
        self.assertNotIn("Font.system(size:", code_only(swift))

    def test_swift_maps_families_to_designs(self):
        from scripts.tokens.emit_swift import emit_swift

        swift = emit_swift(load(SOURCE))
        self.assertIn("design: .monospaced", swift)   # mono roles
        self.assertIn("design: .serif", swift)        # body

    def test_kotlin_emits_type_scale_names_not_sp(self):
        from scripts.tokens.emit_kotlin import emit_kotlin

        kt = emit_kotlin(load(SOURCE))
        self.assertIn("bodyLarge", kt)
        self.assertNotIn(".sp", code_only(kt))

    def test_the_structural_rule_survives_into_every_target(self):
        """serif for the agent, sans for the operator — on all three."""
        from scripts.tokens.emit_kotlin import emit_kotlin
        from scripts.tokens.emit_swift import emit_swift

        swift, kt = emit_swift(load(SOURCE)), emit_kotlin(load(SOURCE))
        self.assertIn("static let body = Font.system(.body, design: .serif)", swift)
        self.assertIn("static let bodyOwn = Font.system(.body)", swift)
        self.assertIn('val body = FontFamily.Serif', kt)
        self.assertIn('val bodyOwn = FontFamily.SansSerif', kt)

class ImportTests(unittest.TestCase):
    """Every symbol the generated code references must be imported.

    This exists because it already happened. Adding the type block to the
    Kotlin emitter introduced `FontFamily` without its import, the whole
    Python suite stayed green, and CI failed with seven `Unresolved
    reference 'FontFamily'` errors — because there is no Kotlin compiler on
    the machine the emitter is written on. A generator that emits code for
    platforms you cannot build has to typecheck its own output at least
    this much.
    """

    #: symbol -> the import that must be present if the symbol is used.
    KOTLIN = {
        "Color(": "androidx.compose.ui.graphics.Color",
        "FontFamily.": "androidx.compose.ui.text.font.FontFamily",
        ".dp": "androidx.compose.ui.unit.dp",
        "@Immutable": "androidx.compose.runtime.Immutable",
    }

    def test_kotlin_imports_everything_it_references(self):
        from scripts.tokens.emit_kotlin import emit_kotlin

        kt = emit_kotlin(load(SOURCE))
        header, body = kt.split("/** The sixteen colour roles", 1)
        for symbol, module in self.KOTLIN.items():
            if symbol in code_only(body):
                with self.subTest(symbol=symbol):
                    self.assertIn(
                        f"import {module}",
                        header,
                        f"the Kotlin uses {symbol} but does not import {module}",
                    )

    def test_kotlin_has_no_unused_imports(self):
        # The mirror failure: Kotlin warns rather than errors on these, so
        # they rot silently. Task 5 left `Color` imported in Theme.kt after
        # the data class moved out.
        from scripts.tokens.emit_kotlin import emit_kotlin

        kt = emit_kotlin(load(SOURCE))
        header, body = kt.split("/** The sixteen colour roles", 1)
        for symbol, module in self.KOTLIN.items():
            if f"import {module}" in header:
                with self.subTest(symbol=symbol):
                    self.assertIn(
                        symbol,
                        code_only(body),
                        f"the Kotlin imports {module} but never uses {symbol}",
                    )

    def test_swift_imports_swiftui(self):
        from scripts.tokens.emit_swift import emit_swift

        swift = emit_swift(load(SOURCE))
        self.assertIn("import SwiftUI", swift)
        # Color, Font and CGFloat all come from SwiftUI (via CoreGraphics);
        # there is no second module to forget, which is why Swift did not
        # break the way Kotlin did.
        for symbol in ("Color(", "Font.system(", "CGFloat"):
            with self.subTest(symbol=symbol):
                self.assertIn(symbol, code_only(swift))

class AppearanceSelectorTests(unittest.TestCase):
    """Every appearance must be explicitly selectable.

    tokens.css reached dark only through a prefers-color-scheme media query,
    so a catalogue could switch to paper but needed the OS theme changed to
    show dark — and on a dark-set machine, light was unreachable entirely.

    Faking the theme in Storybook's own CSS was the alternative, and it
    would mean the catalogue showing something the app cannot produce.
    """

    def setUp(self):
        self.css = emit_app_css(load(SOURCE))

    def test_all_three_are_attribute_selectable(self):
        for name in ("light", "dark", "paper"):
            with self.subTest(name=name):
                self.assertIn(f'[data-appearance="{name}"]', self.css)

    def test_an_explicit_choice_beats_the_os(self):
        """Asserted as ORDER, because order is the actual mechanism.

        An earlier version of this test checked that the string
        ":root:not([data-appearance])" appeared, and called that proof. It
        was not: measured in a dark-set browser, removing the guard changes
        nothing, because an attribute selector and :root share specificity
        (0,1,0) and the explicit blocks are emitted afterwards. The
        substring assertion would have passed against a stylesheet whose
        explicit blocks came FIRST and therefore lost.

        So this asserts the ordering, and separately that the guard is
        present as order-independent insurance.
        """
        media_at = self.css.index("@media (prefers-color-scheme: dark)")
        for name in ("light", "dark", "paper"):
            with self.subTest(name=name):
                self.assertGreater(
                    self.css.index(f'[data-appearance="{name}"]'),
                    media_at,
                    "an explicit appearance block must come after the media "
                    "query, or equal specificity makes the OS win",
                )

    def test_the_guard_is_present_as_order_independent_insurance(self):
        # Not load-bearing today — see the test above — but it is what keeps
        # the behaviour if the blocks are ever reordered.
        self.assertIn(":root:not([data-appearance])", self.css)

    def test_light_is_still_the_bare_default(self):
        # A page that sets no attribute and asks for no scheme must still
        # have a complete palette.
        root = self.css.split("@layer theme")[0]
        for role in ROLES:
            with self.subTest(role=role):
                self.assertIn(f"--color-{role}:", root)

    def test_each_appearance_block_is_complete(self):
        # A partial override inherits the rest from light, which is exactly
        # how a half-applied theme happens and it looks like a palette bug
        # rather than a missing declaration.
        for name in ("light", "dark", "paper"):
            block = self.css.split(f'[data-appearance="{name}"] {{')[1]
            block = block[: block.index("\n  }")]
            for role in ROLES:
                with self.subTest(name=name, role=role):
                    self.assertIn(f"--color-{role}:", block)

    def test_the_explicit_blocks_carry_their_own_appearances_values(self):
        tokens = load(SOURCE)
        for name in ("light", "dark", "paper"):
            block = self.css.split(f'[data-appearance="{name}"] {{')[1]
            block = block[: block.index("\n  }")]
            with self.subTest(name=name):
                self.assertIn(tokens.appearances[name].colors["surface"], block)


if __name__ == "__main__":
    unittest.main()
