import re
import unittest
from pathlib import Path

from scripts.tokens.emit_css import emit_app_css
from scripts.tokens.model import ROLES, load

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "design" / "tokens.toml"
GOLDEN = Path(__file__).parent / "golden"


class AppCssTests(unittest.TestCase):
    def setUp(self):
        self.css = emit_app_css(load(SOURCE))
        self.root = self.css.split("@layer theme")[0]

    def test_it_says_it_is_generated(self):
        self.assertIn("Generated by scripts/generate-tokens.py", self.css)
        self.assertIn("do not edit", self.css.lower())

    def test_light_is_the_bare_root_and_defines_every_role(self):
        for role in ROLES:
            with self.subTest(role=role):
                self.assertIn(f"--color-{role}:", self.root)

    def test_no_colour_is_defined_only_inside_a_media_query(self):
        """A colour whose only definition is in the dark block leaves the
        light theme with nothing. This is the rule app.css already follows
        and the one a generator can enforce for free."""
        declared_anywhere = set(re.findall(r"--color-([a-z-]+):", self.css))
        declared_in_root = set(re.findall(r"--color-([a-z-]+):", self.root))
        self.assertEqual(declared_anywhere - declared_in_root, set())

    def test_dark_is_a_prefers_color_scheme_block(self):
        self.assertIn("@media (prefers-color-scheme: dark)", self.css)

    def test_paper_is_an_attribute_selector_not_the_default(self):
        self.assertIn('[data-appearance="paper"]', self.css)
        self.assertNotIn("#faf8f3", self.root)

    def test_every_appearances_values_actually_reach_the_output(self):
        tokens = load(SOURCE)
        for name, appearance in tokens.appearances.items():
            with self.subTest(appearance=name):
                self.assertIn(appearance.colors["surface"], self.css)
                self.assertIn(appearance.colors["signal"], self.css)

    def test_rationale_reaches_the_output(self):
        self.assertIn("2.92", self.css)

    def test_it_matches_the_golden_file(self):
        self.assertEqual(self.css, (GOLDEN / "app-tokens.css").read_text())


if __name__ == "__main__":
    unittest.main()
