import SupermessageFFI
import SwiftUI

/// The palette and type ramp.
///
/// Colour values come from `design/tokens.toml` via the generated
/// `ThemeTokens`; the rules are in `docs/design-language.md`. The
/// console-design spec remains the record of how the language was arrived
/// at, but it is no longer the authority — being a document three codebases
/// read and re-derived by eye is what this generator exists to end.
///
/// The identity that travels from the desktop is **structural**, not the
/// typefaces: serif for what agents write, sans for what the operator writes,
/// mono for data and sigils, and one colour reserved for one meaning. The
/// faces are the system's — `.serif` resolves to New York, `.monospaced` to SF
/// Mono — so Dynamic Type comes free and nothing is bundled.
/// One `Color` per role per choice per scheme, made once.
///
/// **In the app the scheme is given, not asked for.** A `UIColor` provider
/// asks the trait collection of whatever UIKit container is resolving it,
/// and on iOS 26 the containers inside the tab view are a scheme behind when
/// SwiftUI redraws: the room list resolved the old scheme's colour on every
/// switch and was never asked again (phone log, 2026-09-24 — SwiftUI said
/// dark, the colour came back light). So the root, which is always right,
/// records the scheme in `ThemeState`, and each colour is built for it. Any
/// body that reads one is redrawn when it changes.
///
/// Where nothing records it — a preview, a test host — the scheme is `nil`
/// and the colour stays dynamic, which is how previews have always rendered.
enum ThemeColors {
    private struct Key: Hashable {
        let role: KeyPath<Palette, Color>
        let choice: ThemeChoice
        let scheme: ColorScheme?
    }

    nonisolated(unsafe) private static var made: [Key: Color] = [:]
    private static let lock = NSLock()

    static func color(
        _ role: KeyPath<Palette, Color>, for choice: ThemeChoice, scheme: ColorScheme?
    ) -> Color {
        let key = Key(role: role, choice: choice, scheme: scheme)
        lock.lock()
        defer { lock.unlock() }
        if let color = made[key] { return color }
        let color: Color
        if let scheme {
            color = choice.palette(dark: scheme == .dark)[keyPath: role]
        } else {
            color = Color(
                UIColor { traits in
                    UIColor(choice.palette(dark: traits.userInterfaceStyle == .dark)[keyPath: role])
                })
        }
        made[key] = color
        return color
    }
}

enum Theme {
    // MARK: - Colour
    //
    // **The values live in `design/tokens.toml`** and reach this file as
    // `ThemeTokens`, generated by `scripts/generate-tokens.py`. They used to
    // be written out here, and separately in `src/app.css` and `Theme.kt`,
    // each re-derived by eye from the console-design spec — by 2026-09 none
    // of the three agreed, down to amber being three different ambers.
    //
    // What stays here is the *resolution*: which appearance a trait
    // collection means, and the modifier below that makes a face follow a
    // scheme change. Neither is a value, so neither is generated.

    /// Resolves a role against the current appearance.
    ///
    /// **iOS binds `paper` to light and `dark` to dark**: paper is what
    /// "light" means on a phone. Dark then has a second axis, the account's
    /// dark style, which picks `black` instead; and a curated accent brings
    /// its own palette — its accent, and grounds and greys in its hue.
    ///
    /// **Neither input travels as a trait.** Light or dark is recorded by
    /// the root — see `ThemeColors` for why UIKit is not asked. The
    /// account's choice is not a trait either: build 20 carried it as a custom trait bridged into SwiftUI, and
    /// on iOS 26 a scheme switch then resolved every colour against the old
    /// scheme — SwiftUI said light, the colours came back dark (phone log,
    /// 2026-09-24). The choice is read from `ThemeState` instead; reading it
    /// in a view's body is what makes that view redraw when it changes, and
    /// each choice gets its own `Color`, so a new one is never mistaken for
    /// the old.
    private static func dynamic(_ role: KeyPath<Palette, Color>) -> Color {
        let state = ThemeState.shared
        return ThemeColors.color(role, for: state.choice, scheme: state.scheme)
    }

    /// A sender's colour: one of seven, by `peer_color_index` in the core so
    /// every platform gives a person the same one.
    static func peer(_ userId: String) -> Color {
        let index = Int(peerColorIndex(userId: userId))
        let choice = ThemeState.shared.choice
        if let scheme = ThemeState.shared.scheme {
            let set: [Color]
            if scheme == .dark {
                set = choice.darkStyle == .black ? ThemePeers.black : ThemePeers.dark
            } else {
                set = ThemePeers.paper
            }
            return set[index % set.count]
        }
        return Color(
            UIColor { traits in
                let set: [Color]
                if traits.userInterfaceStyle == .dark {
                    set = choice.darkStyle == .black ? ThemePeers.black : ThemePeers.dark
                } else {
                    set = ThemePeers.paper
                }
                return UIColor(set[index % set.count])
            })
    }

    /// The page itself.
    static var surface: Color { dynamic(\.surface) }
    /// The field the reading sheet sits on: roster, header, composer.
    static var surfaceSunken: Color { dynamic(\.surfaceSunken) }
    /// Behind a chip, a segmented control, an avatar with no picture.
    static var surfaceRaised: Color { dynamic(\.surfaceRaised) }
    /// Hairlines and dividers.
    static var border: Color { dynamic(\.border) }
    static var borderStrong: Color { dynamic(\.borderStrong) }

    /// The three text ranks, and the app now uses them.
    ///
    /// This said adoption was "P6, not this commit", and P6 has happened:
    /// every `foregroundStyle` in the views maps to one of these, and
    /// `RootView` sets `content` for the text that says nothing at all —
    /// which was most of it, and was taking SwiftUI's label colour.
    ///
    /// These three carry contrast contracts in `design/tokens.toml`, and
    /// `content-faint` carries one against all three grounds rather than
    /// only the reading surface. Before this the contracts were asserted at
    /// build time and governed nothing on iOS.
    static var content: Color { dynamic(\.content) }
    static var contentMuted: Color { dynamic(\.contentMuted) }
    static var contentFaint: Color { dynamic(\.contentFaint) }

    /// The chrome hue. Selection, focus, the send button, own bubbles.
    static var accent: Color { dynamic(\.accent) }
    /// `accent` as the app's tint: a dynamic colour UIKit resolves itself.
    ///
    /// The tint reaches UIKit controls — a menu picker's label, a toggle —
    /// and those draw it at the instant light and dark switch. Given the
    /// per-scheme `accent`, which SwiftUI swaps a moment later, a picker in
    /// Account kept the old scheme's pink after every switch (phone,
    /// 2026-09-25). Same cause as `paletteListGround`.
    static var tint: Color {
        ThemeColors.color(\.accent, for: ThemeState.shared.choice, scheme: nil)
    }
    /// What is legible *on* `accent`.
    static var accentContent: Color { dynamic(\.accentContent) }
    static var accentSoft: Color { dynamic(\.accentSoft) }

    /// **Amber, and it means exactly one thing: the operator owes someone an
    /// answer.**
    ///
    /// It appears on a pending decision and nowhere else — not on unread
    /// badges, not on hover, not on warnings, not on the connection bar. Any
    /// other use is a review defect. If you are reaching for this and you
    /// are not drawing a decision, reach for something else.
    static var signal: Color { dynamic(\.signal) }
    /// The ground a pending decision sits on. `signal` clears 6:1 against
    /// it — not 4.5 — because it carries the 10px label.
    static var signalSoft: Color { dynamic(\.signalSoft) }

    static var danger: Color { dynamic(\.danger) }
    /// A room that is working. Never amber — this is good news, and amber is
    /// reserved for what a reader owes.
    static var ok: Color { dynamic(\.ok) }

    /// The veil behind a panel presented over the roster rather than beside
    /// it. Not a fifth hue: the ramp's own end used as a wash.
    static var scrim: Color { dynamic(\.scrim) }

    // MARK: - Type
    //
    // Each style says what it is *for*, not what it looks like, so a caller
    // picks by meaning and the ramp stays consistent.

    /// Anything said in a conversation, by an agent or by you. One face:
    /// who said it is carried by the sender's badge and card, not by a
    /// typeface. From the generated ramp, so every platform agrees.
    static let body = ThemeType.body
    /// What you wrote. The same face as `body`; kept as its own name because
    /// your text is never parsed as markdown.
    static let own = ThemeType.bodyOwn
    /// The long-form reading view for an agent's report — the one place the
    /// serif survives.
    static let longread = ThemeType.longread

    /// Timestamps, counts, receipts. Sans with tabular figures, so columns of
    /// times still line up, in either appearance. Mono made every line of
    /// metadata read as a terminal beside the prose.
    static func meta(dark: Bool) -> Font {
        ThemeType.meta.monospacedDigit()
    }

    /// A room, person or agent name. Semibold sans in both appearances.
    static func name(dark: Bool) -> Font {
        Font.system(.subheadline, weight: .semibold)
    }

    /// Which appearance-dependent face a view wants.
    enum Face { case meta, name }

    /// Code, inline or block.
    static let code = Font.system(.callout, design: .monospaced)
}

/// Applies a face that changes with the appearance.
///
/// **A modifier rather than a static, and that distinction is the bug it
/// fixes.** The faces were computed properties reading
/// `UITraitCollection.current`, which SwiftUI has no reason to observe — so
/// switching between light and dark left the old typography on screen until
/// the app was relaunched. Reading `\.colorScheme` from the environment makes
/// the dependency one SwiftUI tracks, and the change lands immediately.
///
/// The colours needed no such fix: a `UIColor` built from a trait-resolving
/// provider is re-resolved by UIKit on every appearance change already.
private struct ThemedFace: ViewModifier {
    @Environment(\.colorScheme) private var scheme
    let face: Theme.Face

    func body(content: Content) -> some View {
        let dark = scheme == .dark
        return content.font(face == .meta ? Theme.meta(dark: dark) : Theme.name(dark: dark))
    }
}

extension View {
    /// Sigils, roles, timestamps, counts.
    func metaFace() -> some View { modifier(ThemedFace(face: .meta)) }
    /// A room or agent name.
    func nameFace() -> some View { modifier(ThemedFace(face: .name)) }
}
