import SwiftUI

/// The palette and type ramp.
///
/// Colour values come from `design/tokens.toml` via the generated
/// `ThemeTokens`; the rules are in `docs/design-language.md`. The
/// console-design spec remains the record of how the language was arrived
/// at, but it is no longer the authority — being a document three codebases
/// read and re-derived by eye is what this generator exists to end.
///
/// The identity that travels from the desktop is **structural**, not the
/// typefaces: serif for what agents write, sans for what the operator writes,
/// mono for data and sigils, and one colour reserved for one meaning. The
/// faces are the system's — `.serif` resolves to New York, `.monospaced` to SF
/// Mono — so Dynamic Type comes free and nothing is bundled.
enum Theme {
    // MARK: - Colour
    //
    // **The values live in `design/tokens.toml`** and reach this file as
    // `ThemeTokens`, generated by `scripts/generate-tokens.py`. They used to
    // be written out here, and separately in `src/app.css` and `Theme.kt`,
    // each re-derived by eye from the console-design spec — by 2026-09 none
    // of the three agreed, down to amber being three different ambers.
    //
    // What stays here is the *resolution*: which appearance a trait
    // collection means, and the modifier below that makes a face follow a
    // scheme change. Neither is a value, so neither is generated.

    /// Resolves a role against the current appearance.
    ///
    /// **iOS binds `paper` to light and `dark` to dark**: paper is what
    /// "light" means on a phone. That binding is why this needs to know
    /// nothing beyond `userInterfaceStyle` — there is no third state to
    /// detect and no picker to read.
    private static func dynamic(_ role: KeyPath<Palette, Color>) -> Color {
        Color(
            UIColor { traits in
                let palette =
                    traits.userInterfaceStyle == .dark
                    ? ThemeTokens.dark
                    : ThemeTokens.paper
                return UIColor(palette[keyPath: role])
            })
    }

    /// The page itself.
    static let surface = dynamic(\.surface)
    /// The field the reading sheet sits on: roster, header, composer.
    static let surfaceSunken = dynamic(\.surfaceSunken)
    /// Behind a chip, a segmented control, an avatar with no picture.
    static let surfaceRaised = dynamic(\.surfaceRaised)
    /// Hairlines and dividers.
    static let border = dynamic(\.border)
    static let borderStrong = dynamic(\.borderStrong)

    /// The three text ranks. **New to iOS in this change** — the app has
    /// been colouring text with `Color.secondary` and SwiftUI defaults, so
    /// the hierarchy the type ramp assumes did not exist here at all.
    /// Adopting them across the views is P6, not this commit.
    static let content = dynamic(\.content)
    static let contentMuted = dynamic(\.contentMuted)
    static let contentFaint = dynamic(\.contentFaint)

    /// The chrome hue. Selection, focus, the send button, own bubbles.
    static let accent = dynamic(\.accent)
    /// What is legible *on* `accent`.
    static let accentContent = dynamic(\.accentContent)
    static let accentSoft = dynamic(\.accentSoft)

    /// **Amber, and it means exactly one thing: the operator owes someone an
    /// answer.**
    ///
    /// It appears on a pending decision and nowhere else — not on unread
    /// badges, not on hover, not on warnings, not on the connection bar. Any
    /// other use is a review defect. If you are reaching for this and you
    /// are not drawing a decision, reach for something else.
    static let signal = dynamic(\.signal)
    /// The ground a pending decision sits on. `signal` clears 6:1 against
    /// it — not 4.5 — because it carries the 10px label.
    static let signalSoft = dynamic(\.signalSoft)

    static let danger = dynamic(\.danger)
    /// A room that is working. Never amber — this is good news, and amber is
    /// reserved for what a reader owes.
    static let ok = dynamic(\.ok)

    /// The veil behind a panel presented over the roster rather than beside
    /// it. Not a fifth hue: the ramp's own end used as a wash.
    static let scrim = dynamic(\.scrim)

    // MARK: - Type
    //
    // Each style says what it is *for*, not what it looks like, so a caller
    // picks by meaning and the ramp stays consistent.

    /// What an agent wrote. Serif, because the timeline is a reading surface.
    static let body = Font.system(.body, design: .serif)
    /// What the operator wrote. Sans — a command, not prose.
    static let own = Font.system(.body)
    /// Sigils, roles, timestamps, counts. Data.
    ///
    /// **Monospaced on Paper, plain on Slate**, and that is a legibility
    /// decision rather than a stylistic one: SF Mono at caption size on a dark
    /// ground loses its counters and greys out, while on warm paper it reads
    /// as the record-keeping it is. Tabular figures are kept either way, so
    /// columns of timestamps still line up.
    static func meta(dark: Bool) -> Font {
        Font.system(.caption, design: dark ? .default : .monospaced).monospacedDigit()
    }

    /// A room or agent name.
    ///
    /// **Serif on Paper, sans on Slate.** The serif name is what makes the
    /// roster read as a record rather than a chat app, and it rhymes with the
    /// timeline's prose; on Slate the same face goes thin and the sans holds
    /// up better.
    static func name(dark: Bool) -> Font {
        dark
            ? Font.system(.subheadline, weight: .semibold)
            : Font.system(.subheadline, design: .serif, weight: .semibold)
    }

    /// Which appearance-dependent face a view wants.
    enum Face { case meta, name }

    /// Code, inline or block.
    static let code = Font.system(.callout, design: .monospaced)
}

/// Applies a face that changes with the appearance.
///
/// **A modifier rather than a static, and that distinction is the bug it
/// fixes.** The faces were computed properties reading
/// `UITraitCollection.current`, which SwiftUI has no reason to observe — so
/// switching between light and dark left the old typography on screen until
/// the app was relaunched. Reading `\.colorScheme` from the environment makes
/// the dependency one SwiftUI tracks, and the change lands immediately.
///
/// The colours needed no such fix: a `UIColor` built from a trait-resolving
/// provider is re-resolved by UIKit on every appearance change already.
private struct ThemedFace: ViewModifier {
    @Environment(\.colorScheme) private var scheme
    let face: Theme.Face

    func body(content: Content) -> some View {
        let dark = scheme == .dark
        return content.font(face == .meta ? Theme.meta(dark: dark) : Theme.name(dark: dark))
    }
}

extension View {
    /// Sigils, roles, timestamps, counts.
    func metaFace() -> some View { modifier(ThemedFace(face: .meta)) }
    /// A room or agent name.
    func nameFace() -> some View { modifier(ThemedFace(face: .name)) }
}
